### ISSUE TITLE
Implement IBC transfer pallet 

### ISSUE THREAD

**Issue by Wizdave97** [ComposableFi/composable#1044]
**Description**

This pallet implementation should handle all the on-chain logic for the ibc interchain transfer protocol.

This would mostly involve implementing the `ICS20Context` trait as defined in `ibc-rs` and the packet call back traits.

**Comment by Wizdave97** [comment]
Currently blocked by #1034

**Comment by seunlanlege** [comment]
for the bank module i suggest we use the `Currency` trait for dealing with balances and minting and withdrawing

**Comment by Wizdave97** [comment]
> for the bank module i suggest we use the [`Currency`](https://docs.substrate.io/rustdocs/latest/frame_support/traits/tokens/currency/trait.Currency.html) trait for dealing with balances and minting and withdrawing. This way we can swap out pallet-balances for t

Yeah was going to go with `MultiCurrency`
