### ISSUE TITLE
Update Events returned by rpc interface

### ISSUE THREAD

**Issue by Wizdave97** [ComposableFi/composable#1281]
**Motivation**

Currently the ibc events returned by the rpc interface uses a custom event enum

**Suggested Solution**

Return ibc-rs events instead

**Alternatives**

_Describe any alternative solutions or features you considered and why you believe your suggested
solution is preferable._

**Additional Information**

_Provide any additional information that you believe may help us evaluate your suggestion._

**Comment by seunlanlege** [comment]
💪🏿
