### ISSUE TITLE
move all custom host functions 🫠 to wasm

### ISSUE THREAD

**Issue by seunlanlege** [ComposableFi/composable#1308]
<img width="1446" alt="Screenshot 2022-07-12 at 3 29 25 PM" src="https://user-images.githubusercontent.com/16494314/178501719-8228463b-a08d-4ee8-83a1-c21d182a8bc6.png">

**Comment by blasrodri** [comment]
Why do we need to move the host functions to wasm instead of adding the host functions into all the chains?

**Comment by seunlanlege** [comment]
No one's going to go for that, especially not parity.
