### ISSUE TITLE
is XCVM protobuf specification is deterministic?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/composable#1629]
From Cosmos:

> Because protobuf is not deterministic, it has been decided in [ADR-020](https://docs.cosmos.network/main/architecture/adr-020-protobuf-transaction-encoding.html) that the canonical payload to sign is the SignDoc struct, deterministically encoded using [ADR-027](https://docs.cosmos.network/main/architecture/adr-027-deterministic-protobuf-serialization.html)

**Comment by KaiserKarel** [comment]
It depends on the encoder/decoder implementation. The spec does not define 1 encoding for a certain payload (key ordering eg), but implementations can opt-in. We might need to fork for this though.

**Comment by dzmitry-lahoda** [comment]
https://github.com/cosmos/cosmos-sdk/blob/main/docs/architecture/adr-027-deterministic-protobuf-serialization.md

**Comment by dzmitry-lahoda** [comment]
https://github.com/cosmos/cosmos-sdk/tree/main/docs/architecture

**Comment by dzmitry-lahoda** [comment]
closing until it will become bug https://composablefinance.slack.com/archives/C03B8BN8ULX/p1665390751719349
