### ISSUE TITLE
Security email bounces

### ISSUE THREAD

**Issue by gilescope** [ComposableFi/composable#1630]
"The report should be submitted to [security@composable.finance](mailto:security@composable.finance)."

The mailserver tells me that mailbox wasn't found.

**Comment by KaiserKarel** [comment]
Hiya gilescope! We're checking it out right now. If you have a report, you can forward it to fdr@composable.finance (our head of security) until we fix the issue.

**Comment by hussein-aitlahcen** [comment]
@gilescope the email is **reporting@composable.finance**, fixed by #1701. Note that the email might only be ready by the end of the day.
