### ISSUE TITLE
fix nix flake check

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/composable#1641]
**Motivation**

so we randomly break people workflows modifying nix

**Suggested Solution**

https://github.com/ComposableFi/composable/pull/1621

**Alternatives**

run arion up in CI, wait and stop after started.

arion is not package - cannot build.

**Comment by hussein-aitlahcen** [comment]
Probably nice to refactor arion expression and have custom `docker-compose` package so that we build the file only

**Comment by dzmitry-lahoda** [comment]
is it capability of arion, or need to expose underlying layer of it, or wrap arion into package to expose?

flake utils overrride fixes all

**Comment by dzmitry-lahoda** [comment]
https://github.com/ComposableFi/composable/blob/nix/v1/.nix/override-input/flake-utils/flake.nix

**Comment by dzmitry-lahoda** [comment]
https://github.com/numtide/flake-utils/issues/80
