### ISSUE TITLE
bake #nix oci image to run in #ci to avoid throttling/ratelimiting and speed up #ci

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/composable#2299]
**Motivation**

Our CI started to bompard API and they started 429 (rate limit, throttle us). Specifically nix

```
Cachix: installing
  /run/profile/bin/bash -c nix-channel --add https://nixos.org/channels/nixpkgs-22.05-darwin nixpkgs
  nix-channel --update
  nix-env -iA nixpkgs.cachix
  warning: error: unable to download 'https://nixos.org/channels/nixpkgs-[22](https://github.com/ComposableFi/composable/actions/runs/3465945234/jobs/5789259229#step:5:23).05-darwin': HTTP error 301 ('') (curl error: Timeout was reached); retrying in 292 ms
  warning: error: unable to download 'https://nixos.org/channels/nixpkgs-22.05-darwin': HTTP error 301 ('') (curl error: Timeout was reached); retrying in 692 ms
  warning: error: unable to download 'https://nixos.org/channels/nixpkgs-22.05-darwin': HTTP error 301 ('') (curl error: Timeout was reached); retrying in 1118 ms
  warning: error: unable to download 'https://nixos.org/channels/nixpkgs-22.05-darwin': HTTP error 301 ('') (curl error: Timeout was reached); retrying in [25](https://github.com/ComposableFi/composable/actions/runs/3465945234/jobs/5789259229#step:5:26)14 ms
  error: unable to download 'https://nixos.org/channels/nixpkgs-22.05-darwin': HTTP error [30](https://github.com/ComposableFi/composable/actions/runs/3465945234/jobs/5789259229#step:5:31)1 ('') (curl error: Timeout was reached)
  error: attribute 'nixpkgs' in selection path 'nixpkgs.cachix' not found
  Error: Action failed with error: Error: The process '/run/profile/bin/bash' failed with exit code 1
```

https://github.com/ComposableFi/composable/actions/runs/3465945234/jobs/5789259229

**Suggested Solution**

Bake Nix image with channel and some other basic setup. Hopefully rebuild on each merge to master and conditionally push if that changes (so we get new tooling).

Use that image as base CI image.

**Alternatives**

- Other forms of getting updated nix channel state.
- Do not use shared nix channel (own our channel).

**Comment by KaiserKarel** [comment]
Agreed. In the mean time are there parties we can contact to whitelist IPs?

**Comment by dzmitry-lahoda** [comment]
```
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ curl -L https://nixos.org/channels/nixpkgs-22.05-darwin > out.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    63  100    63    0     0    224      0 --:--:-- --:--:-- --:--:--   224
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1990  100  1990    0     0   3173      0 --:--:-- --:--:-- --:--:--  3173
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$
```

**Comment by dzmitry-lahoda** [comment]
Leaving GHCi.
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ curl https://nixos.org/channels/nixpkgs-22.05-darwin
Redirecting to https://channels.nixos.org/nixpkgs-22.05-darwindz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ ls
Code.VisualElementsManifest.xml  ffmpeg.dll     resources          unins000.msg
Code.exe                         icudtl.dat     resources.pak      v8_context_snapshot.bin
bin                              libEGL.dll     snapshot_blob.bin  vk_swiftshader.dll
chrome_100_percent.pak           libGLESv2.dll  tools              vk_swiftshader_icd.json
chrome_200_percent.pak           locales        unins000.dat       vulkan-1.dll
d3dcompiler_47.dll               policies       unins000.exe
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ curl -L https://nixos.org/channels/nixpkgs-22.05-darwin
<html><head><title>nixpkgs-22.05-darwin release nixpkgs-darwin-22.05pre384075.29d9eb59c00</title></head><body><h1>nixpkgs-22.05-darwin release nixpkgs-darwin-22.05pre384075.29d9eb59c00</h1><p>Released on 2022-11-14 20:44:48 from <a href='https://github.com/NixOS/nixpkgs/commits/29d9eb59c00d8eeeff228e039ac0b4ee651181fa'>Git commit <tt>29d9eb59c00d8eeeff228e039ac0b4ee651181fa</tt></a> via <a href='https://hydra.nixos.org/eval/1785474'>Hydra evaluation 1785474</a>.</p><table><thead><tr><th>File name</th><th>Size</th><th>SHA-256 hash</th></tr></thead><tbody><tr><td><a href='/nixpkgs/22.05-darwin/nixpkgs-darwin-22.05pre384075.29d9eb59c00/binary-cache-url'>binary-cache-url</a></td><td align='right'>23</td><td><tt>eb8d2a51d85521c07092ed8126df19bb6f9d7c16a5275395a0e110868a4ac6c0</tt></td></tr><tr><td><a href='/nixpkgs/22.05-darwin/nixpkgs-darwin-22.05pre384075.29d9eb59c00/git-revision'>git-revision</a></td><td align='right'>40</td><td><tt>04c8637e4b8e3cb31f331c70b01651f0ce34248e0bbafe3c915904553b8ec4cd</tt></td></tr><tr><td><a href='/nixpkgs/22.05-darwin/nixpkgs-darwin-22.05pre384075.29d9eb59c00/nixexprs.tar.xz'>nixexprs.tar.xz</a></td><td align='right'>21229064</td><td><tt>24156749a8b5edd351eadc88184da812069178335b35805dc23497014de09f7c</tt></td></tr><tr><td><a href='/nixpkgs/22.05-darwin/nixpkgs-darwin-22.05pre384075.29d9eb59c00/packages.json.br'>packages.json.br</a></td><td align='right'>4118584</td><td><tt>552a2eb3db526d3891ef81b4f3427e1d42185055ab98cc29a8548abbf0d4a793</tt></td></tr><tr><td><a href='/nixpkgs/22.05-darwin/nixpkgs-darwin-22.05pre384075.29d9eb59c00/src-url'>src-url</a></td><td align='right'>36</td><td><tt>6360b3b41dd2cbfa4530a155a6d87cfc6dae3ec2710b0cedcdbe455c93062cb3</tt></td></tr><tr><td><a href='/nixpkgs/22.05-darwin/nixpkgs-darwin-22.05pre384075.29d9eb59c00/store-paths.xz'>store-paths.xz</a></td><td align='right'>2013904</td><td><tt>be2c384cc72fe34c80fa50a43de7d92c8e61f72a5f5a8fc324c7c3f1dc5b1142</tt></td></tr></tbody></table></body></html>dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ ^C
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ ^C
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ curl -L https://nixos.org/channels/nixpkgs-22.05-darwin > out.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    63  100    63    0     0    224      0 --:--:-- --:--:-- --:--:--   224
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1990  100  1990    0     0   3173      0 --:--:-- --:--:-- --:--:--  3173
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix-channel --update
this derivation will be built:
  /nix/store/0hx3s9yrak21chiz805z57i8m9i77k1x-nixpkgs.drv
building '/nix/store/0hx3s9yrak21chiz805z57i8m9i77k1x-nixpkgs.drv'...
this derivation will be built:
  /nix/store/zcmph2nz8pbjp5cif9afahcl1bbniia0-rust-overlay.drv
building '/nix/store/zcmph2nz8pbjp5cif9afahcl1bbniia0-rust-overlay.drv'...
unpacking channels...
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix-channel --list
nixpkgs https://github.com/NixOS/nixpkgs/archive/aaa1c973c8c189195e1b1a702d3b74dbcde91538.tar.gz
rust-overlay https://github.com/oxalica/rust-overlay/archive/master.tar.gz
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix-channel
error: no command specified
Try 'nix-channel --help' for more information.
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix-channel add
error: no command specified
Try 'nix-channel --help' for more information.
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix-channel --help
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix-channel --add https://nixos.org/channels/nixpkgs-22.05-darwin nixpkgs
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix-channel add
error: no command specified
Try 'nix-channel --help' for more information.
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-22.05-darwin
rust-overlay https://github.com/oxalica/rust-overlay/archive/master.tar.gz
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix-channel --update
unpacking channels...
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix-channel --update
unpacking channels...
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$   nix-env -iA nixpkgs.cachix
error: profile '/nix/var/nix/profiles/per-user/dz/profile' is incompatible with 'nix-env'; please use 'nix profile' instead
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix-^Cannel --update
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix profile -iA nixpkgs.cachix
error: unrecognised flag '-i'
Try 'nix --help' for more information.
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix profile --install nixpkgs.cachix
error: unrecognised flag '--install'
Try 'nix --help' for more information.
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix profile -p nixpkgs.cachix
error: unrecognised flag '-p'
Try 'nix --help' for more information.
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix profile
error: 'nix profile' requires a sub-command.
Try 'nix --help' for more information.
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix profile --help
    Warning: This program is experimental and its interface is subject to change.

Name

    nix profile - manage Nix profiles

Synopsis

    nix profile [option...] subcommand

    where subcommand is one of the following:

    · nix profile diff-closures - show the closure difference between each version of a profile
    · nix profile history - show all versions of a profile
    · nix profile install - install a package into a profile
    · nix profile list - list installed packages
    · nix profile remove - remove packages from a profile
    · nix profile rollback - roll back to the previous version or a specified version of a profile
    · nix profile upgrade - upgrade packages using their most recent flake
    · nix profile wipe-history - delete non-current versions of a profile

Description

    nix profile allows you to create and manage Nix profiles. A Nix profile is a set of packages that can be installed and upgraded
    independently from each other. Nix profiles are versioned, allowing them to be rolled back easily.

Default profile

    The default profile used by nix profile is $HOME/.nix-profile, which, if it does not exist, is created as a symlink to
    /nix/var/nix/profiles/per-user/default if Nix is invoked by the root user, or /nix/var/nix/profiles/per-user/username otherwise.

    You can specify another profile location using --profile path.

dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix profile install nixpkgs.cachix
path '/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code/nixpkgs.cachix' does not contain a 'flake.nix', searching up
error: getting status of '/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code/nixpkgs.cachix': No such file or directory
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix profile install cachix
error: cannot find flake 'flake:cachix' in the flake registries
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix profile install --help
    Warning: This program is experimental and its interface is subject to change.

Name

    nix profile install - install a package into a profile

Synopsis

    nix profile install [option...] installables...

Examples

    · Install a package from Nixpkgs:

          | # nix profile install nixpkgs#hello

    · Install a package from a specific branch of Nixpkgs:

          | # nix profile install nixpkgs/release-20.09#hello

    · Install a package from a specific revision of Nixpkgs:

          | # nix profile install nixpkgs/d73407e8e6002646acfdef0e39ace088bacc83da#hello

    · Install a specific output of a package:

          | # nix profile install nixpkgs#bash^man

Description

    This command adds installables to a Nix profile.

Options
dz@dz-pc-11:/mnt/c/Users/dz/AppData/Local/Programs/Microsoft VS Code$ nix profile install nixpkgs#cachix
[32.7 MiB DL]

**Comment by dzmitry-lahoda** [comment]
just added prove it is not really 301 :)

**Comment by dzmitry-lahoda** [comment]
@cor did you talked to Hercules team ? 

<img width="889" alt="image" src="https://user-images.githubusercontent.com/757125/201796702-6af0995c-1eee-40a5-8e7f-212a14ebf4ad.png">

May be they host of packages/cache defaults?
