### ISSUE TITLE
#devops improve our dali(and picasso) collator hosting (parameters, keys)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/composable#2352]
**Motivation**

- our collators cli params are not aligned with other collators which leads to issues running withing expected runners (zombienet) or manual runs
- we forced to use 3 collators while could use 2
- we have potential insecurity if some feature enabled

**Suggested Solution**

1. Dali Dev (local) to have 2 keys, not 3 - for build int collators - less nodes to run
```
	dali::ChainSpec::from_genesis(
		"Local Dali Testnet",
		"dali",
		ChainType::Development,
		move || {
			dali::genesis_config(
				account_id_from_seed::<sr25519::Public>("Alice"),
				vec![
					(
						account_id_from_seed::<sr25519::Public>("Alice"),
						get_collator_keys_from_seed("Alice"),
					),
					(
						account_id_from_seed::<sr25519::Public>("Bob"),
						get_collator_keys_from_seed("Bob"),
					),
   // REMOVE THIS AND TEST collators working
					(
						account_id_from_seed::<sr25519::Public>("Charlie"),
						get_collator_keys_from_seed("Charlie"),
					),
				],
```

2. receive `--parachain-id` like zombinet does, not ad hoc dash split
```
#[cfg(feature = "dali")]
// chain spec for local testnet environments
pub fn dali_dev(id: &str) -> dali::ChainSpec {
	let para_id = match id.split('-').nth(1).expect("Dali chainspec 'dali-dev' has a dash; qed") {
		"dev" => None,
		number => number.parse::<u32>().ok().map(ParaId::from),
	};
	let para_id = para_id.unwrap_or(*PARA_ID);
	let mut properties = Properties::new();
```

Nor do `COMPOSABLE_PARA_ID` -> parachain_id.

Use clap to read both.

3. put next behind and(dali, ocw)

```
	#[cfg(feature = "ocw")]
	{
		let keystore = params.keystore_container.sync_keystore();
		if parachain_config.offchain_worker.enabled {
			// Initialize seed for signing transaction using off-chain workers. This is a
			// convenience so learners can see the transactions submitted simply running the node.
			// Typically these keys should be inserted with RPC calls to `author_insertKey`.
			// TODO(Jesse): remove in prod
			{
				sp_keystore::SyncCryptoStore::sr25519_generate_new(
					&*keystore,
					KeyTypeId(*b"orac"),
					Some("//Alice"),
				)
				.expect("Creating key with account Alice should succeed.");
			}
		}
	}
````

4.  set protocolId = "pica" into genesis, instead of null. e.g. like other chains do `  "protocolId": "dot",`

5. replace ChainType.Development to Local in dali-local for better defaults

<img width="953" alt="image" src="https://user-images.githubusercontent.com/757125/202671314-4dd5a73e-efee-4506-82ed-8d3999317307.png">

6. fork-off-substrate consider `build-spec --dev` to be default dev chain - we do not have `dev` spec mapping (should be dali-dev). so it fails as basis chain

7. You cannot set cumulus_based = false and set own node key and para id.

8. And force setting our own node key template is important because our dev chains fails otherwise (so it can/should be checked too why we ignore injected node keys - may be our genesis is not same structure as others)

**Alternatives**

Suffer from being adhoc and not aligned with ecosystem, and harder to run infra and may be not secure.

**Comment by KaiserKarel** [comment]
Yeah definitely let's not do alternative, and instead align with wider ecosystem

**Comment by dzmitry-lahoda** [comment]
6. You cannot set cumulus_based = false and set own node key and para id.
7. And force setting our own node key template is important because our dev chains fails otherwise (so it can/should be checked too why we ignore injected node keys - may be our genesis is not same structure as others)
