### ISSUE TITLE
update #nix on #ci from 2.8.1 to latest stable

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/composable#2409]
**Motivation**

- updates may have improvements and fixes
- locally people assumed to have latest stable, so we make CI as close as possible to local
- https://github.com/serokell/nix-npm-buildpackage/pull/54#issuecomment-1325734551
- UPDATE: seems it can help with latest crane run too

**Suggested Solution**

- update nixos docker image in ci to latest stable

**Alternatives**

do nothing

**Comment by KaiserKarel** [comment]
Are you creating this PR, or can I pick this up? Working on CI anyways.

**Comment by dzmitry-lahoda** [comment]
No. I not working on it. It does not block me as I found workarounds. 

I did not update myself as afraid it will fail many things and need to spend some time to fix them. So it is not simply nix updates and string replace in yaml.

**Comment by dzmitry-lahoda** [comment]
replaced with CU item

**Comment by dzmitry-lahoda** [comment]
https://app.clickup.com/t/86698q1nm
