### ISSUE TITLE
RFC to Refactor assets-registry to in the assets registry pallet to include DOT

### ISSUE THREAD

**Issue by blasrodri** [ComposableFi/composable#3076]
As part of integrating Pallet IBC into `{Composable, Picasso}` we need to track assets. As far as I understand, bridged assets (thru IBC & XCM) need to be registered in the asset registry pallet.

**Comment by dzmitry-lahoda** [comment]
I would prefer this task will be on me and I can do after RFC0013 is merged.  we have several dicussion how to do integration https://composablefinance.slack.com/archives/C04NT7NF23F/p1676025629855269  . if it finalized that way imho all will be happy.

please create task in CU and close this one regardless.
