### ISSUE TITLE
'Critical database error: Compression

### ISSUE THREAD

**Issue by King-Charming** [ComposableFi/composable#3242]
Mar 02 19:51:08 frhb78254ds Picasso[6748]: 2023-03-02 19:51:08 [Parachain] 💔 Error importing block 0x1c864a78565035f82814a170c2564d7c8559f0f718c07ed2260095feb0dfda37: consensus error: Import failed: Database
Mar 02 19:51:08 frhb78254ds Picasso[6748]: ====================
Mar 02 19:51:08 frhb78254ds Picasso[6748]: Version: 2.10009.0-a75ee48d221a81299d91eb5eac873742a2718aa2
Mar 02 19:51:08 frhb78254ds Picasso[6748]:    0: sp_panic_handler::set::{{closure}}
Mar 02 19:51:08 frhb78254ds Picasso[6748]:    1: std::panicking::rust_panic_with_hook
Mar 02 19:51:08 frhb78254ds Picasso[6748]:    2: std::panicking::begin_panic_handler::{{closure}}
Mar 02 19:51:08 frhb78254ds Picasso[6748]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Mar 02 19:51:08 frhb78254ds Picasso[6748]:    4: rust_begin_unwind
Mar 02 19:51:08 frhb78254ds Picasso[6748]:    5: core::panicking::panic_fmt
Mar 02 19:51:08 frhb78254ds Picasso[6748]:    6: <sc_client_db::parity_db::DbAdapter as sp_database::Database<H>>::get
Mar 02 19:51:08 frhb78254ds Picasso[6748]:    7: sc_client_db::utils::read_db
Mar 02 19:51:08 frhb78254ds Picasso[6748]:    8: <sc_client_db::BlockchainDb<Block> as sp_blockchain::backend::Backend<Block>>::body
Mar 02 19:51:08 frhb78254ds Picasso[6748]:    9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   10: futures_util::stream::stream::StreamExt::poll_next_unpin
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   11: <futures_util::stream::futures_ordered::FuturesOrdered<Fut> as futures_core::stream::Stream>::poll_next
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   12: <futures_util::stream::stream::collect::Collect<St,C> as core::future::future::Future>::poll
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   13: <futures_util::future::join_all::JoinAll<F> as core::future::future::Future>::poll
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   15: <futures_util::stream::stream::for_each::ForEach<St,Fut,F> as core::future::future::Future>::poll
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   17: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   18: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   20: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   21: tokio::runtime::task::core::Core<T,S>::poll
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   22: tokio::runtime::task::harness::Harness<T,S>::poll
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   23: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   24: tokio::runtime::scheduler::multi_thread::worker::Context::run
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   25: tokio::macros::scoped_tls::ScopedKey<T>::set
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   26: tokio::runtime::scheduler::multi_thread::worker::run
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   27: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   28: tokio::runtime::task::core::Core<T,S>::poll
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   29: tokio::runtime::task::harness::Harness<T,S>::poll
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   30: tokio::runtime::blocking::pool::Inner::run
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   31: std::sys_common::backtrace::__rust_begin_short_backtrace
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   32: core::ops::function::FnOnce::call_once{{vtable.shim}}
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   33: std::sys::unix::thread::Thread::new::thread_start
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   34: start_thread
Mar 02 19:51:08 frhb78254ds Picasso[6748]:   35: clone3
Mar 02 19:51:08 frhb78254ds Picasso[6748]: Thread 'tokio-runtime-worker' panicked at 'Critical database error: Compression', /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vendor-cargo-deps/ac66a21da7243416651e94d1f9973a61423c8c90b2fe66658a6fb21ea14acde4/sc-client-db-0.10.0-dev/src/parity_db.rs:31
Mar 02 19:51:08 frhb78254ds Picasso[6748]: This is a bug. Please report it at:
Mar 02 19:51:08 frhb78254ds Picasso[6748]:         https://github.com/ComposableFi/composable/issues/new

**Comment by dzmitry-lahoda** [comment]
please provide context of runs

**Comment by dzmitry-lahoda** [comment]
close as no response
