### ISSUE TITLE
Thread 'main' panicked at 'Route from finalized to leaf should be available

### ISSUE THREAD

**Issue by King-Charming** [ComposableFi/composable#3250]
Mar 05 10:45:52 frhb78254ds Picasso[152905]: Version: 2.10009.0-a75ee48d221a81299d91eb5eac873742a2718aa2
Mar 05 10:45:52 frhb78254ds Picasso[152905]:    0: sp_panic_handler::set::{{closure}}
Mar 05 10:45:52 frhb78254ds Picasso[152905]:    1: std::panicking::rust_panic_with_hook
Mar 05 10:45:52 frhb78254ds Picasso[152905]:    2: std::panicking::begin_panic_handler::{{closure}}
Mar 05 10:45:52 frhb78254ds Picasso[152905]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Mar 05 10:45:52 frhb78254ds Picasso[152905]:    4: rust_begin_unwind
Mar 05 10:45:52 frhb78254ds Picasso[152905]:    5: core::panicking::panic_fmt
Mar 05 10:45:52 frhb78254ds Picasso[152905]:    6: core::result::unwrap_failed
Mar 05 10:45:52 frhb78254ds Picasso[152905]:    7: cumulus_client_consensus_common::level_monitor::LevelMonitor<Block,BE>                                             ::new
Mar 05 10:45:52 frhb78254ds Picasso[152905]:    8: composable_node::service::new_partial
Mar 05 10:45:52 frhb78254ds Picasso[152905]:    9: composable_node::service::start_node_impl::{{closure}}
Mar 05 10:45:52 frhb78254ds Picasso[152905]:   10: <core::future::from_generator::GenFuture<T> as core::future::future::F                                             uture>::poll
Mar 05 10:45:52 frhb78254ds Picasso[152905]:   11: tokio::runtime::park::CachedParkThread::block_on
Mar 05 10:45:52 frhb78254ds Picasso[152905]:   12: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
Mar 05 10:45:52 frhb78254ds Picasso[152905]:   13: tokio::runtime::runtime::Runtime::block_on
Mar 05 10:45:52 frhb78254ds Picasso[152905]:   14: sc_cli::runner::Runner<C>::run_node_until_exit
Mar 05 10:45:52 frhb78254ds Picasso[152905]:   15: composable_node::command::run
Mar 05 10:45:52 frhb78254ds Picasso[152905]:   16: composable::main
Mar 05 10:45:52 frhb78254ds Picasso[152905]:   17: std::sys_common::backtrace::__rust_begin_short_backtrace
Mar 05 10:45:52 frhb78254ds Picasso[152905]:   18: std::rt::lang_start::{{closure}}
Mar 05 10:45:52 frhb78254ds Picasso[152905]:   19: std::rt::lang_start_internal
Mar 05 10:45:52 frhb78254ds Picasso[152905]:   20: main
Mar 05 10:45:52 frhb78254ds Picasso[152905]:   21: __libc_start_call_main
Mar 05 10:45:52 frhb78254ds Picasso[152905]:   22: __libc_start_main_alias_1
Mar 05 10:45:52 frhb78254ds Picasso[152905]:   23: _start
Mar 05 10:45:52 frhb78254ds Picasso[152905]: Thread 'main' panicked at 'Route from finalized to leaf should be available;                                              qed: UnknownBlock("Header was not found in the database: 0x826b5cfb3c344623c5e3b162c0d9a346ee6c6b134ecfc9fc8adb794facdcd                                             f61")', /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vendor-cargo-deps/c25fac3daa102349c17265650b2eff41f2de79eb8d6c435a977                                             3f4b5c576c64a/cumulus-client-consensus-common-0.1.0/src/level_monitor.rs:115
Mar 05 10:45:52 frhb78254ds Picasso[152905]: This is a bug. Please report it at:
Mar 05 10:45:52 frhb78254ds Picasso[152905]:         https://github.com/ComposableFi/composable/issues/new

**Comment by dzmitry-lahoda** [comment]
please provide context on how you run into issue

**Comment by dzmitry-lahoda** [comment]
close as no response
