### ISSUE TITLE
Add $DOT as BYOG option on Picasso parachain 

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/composable#3329]
**Why**
For DOT bridgers who transfer DOT over to Picasso. If they don't have KSM/PICA/USDT to begin with, then they'll be unable to pay gas fee and be stranded. 

**What** 
Add $DOT as BYOG option on Picasso parachain so DOT bridgers can use $DOT for gas fee when performing their first tx on Kusama side e.g swap on Pablo

**Comment by josietyleung** [comment]
@dzmitry-lahoda is this done? thanks!

**Comment by kollegian** [comment]
@dzmitry-lahoda Only tested byog on composable with DOT. Didn't know we also added DOT as an option on Picasso. Will check and update here.

**Comment by kollegian** [comment]
@josietyleung @dzmitry-lahoda validated that the dot is also added as an option on BYOG on picasso and working fine.

**Comment by josietyleung** [comment]
@kollegian amazing thank you
