### ISSUE TITLE
Error running target/release/tmp in --dev mode

### ISSUE THREAD

**Issue by KevinRNelson** [ComposableFi/composable#336]
**Description**

I am trying to setup a development composable node (similar to https://github.com/substrate-developer-hub/substrate-node-template) to practice around with the Apollo Oracle pallet. When I follow the instructions in the readme (listed below) I am given an error saying there is no dev spec file. If I remove the --dev option the node is able to start up, however it is not in dev mode. I can provide more information if needed.

**Steps to Reproduce**

I followed these instructions:
        1. rustup update
        2. rustup update nightly
        3. rustup target add wasm32-unknown-unknown --toolchain nightly
        4. git clone https://github.com/composableFi/composable
        5. cd composable/
        6. sh scripts/init.sh
        7. cargo build --release
        8. ./target/release/composable --dev --tmp

**Expected vs. Actual Behavior**

Expected: 
        start up a node in dev mode
Actual: 
        Error: Input("Error opening spec file `dev`: No such file or directory (os error 2)")

**Environment**

- Operating system: 
        Ubuntu 20.04 LTS running on WSL2 on Windows 10 PC
- Template version/tag:
- Rust version (run `rustup show`):
        active toolchain
        ----------------
        stable-x86_64-unknown-linux-gnu (default)
        rustc 1.56.1 (59eed8a2a 2021-11-01)

**Additional Information**

I have been able to run the substrate-node-template through my setup

**Comment by hussein-aitlahcen** [comment]
Closing as this should be fixed. Let's reopen the issue if you still have trouble running the devnet.
