### ISSUE TITLE
Optimise steps to launch an oracle

### ISSUE THREAD

**Issue by itsbobbyzz** [ComposableFi/composable#3361]
Brett will optimise the steps to launch an oracle,a nd run Rob through so that we can re-write a fit for purpose guide and re-publish this on docs.

Kostya is also working on a detailed technical guide for the oracle eg pallet, extrinsics, etc

Context
- current guide is outdated
- it is focused on getting the oracle set up in devnet (prior to the oracle being on picasso)

Current guide: 
- https://docs.composable.finance/developer-guides/oracle-set-up-guide [OUTDATED]

**Comment by blasrodri** [comment]
@kkast
