### ISSUE TITLE
Asset Registry Update: PICA from Cosmos is still native PICA, not ibcPICA 

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/composable#3365]
**Why**
PICA will have a shared supply across Dotsama + Cosmos ecosystem, so the PICA bridged across from Banksy > Picasso should still be a native PICA in Dotsama

**What**
Update asset registry? or somewhere, so that:
1. PICA bridged across from Banksy > Picasso is not an ibc token, but a native PICA
2. PICA bridged across from Banksy is a flat fee asset, with price taken from Pablo tools 
3. Note that other assets bridged across should still be labelled as ibc token.

**Comment by dzmitry-lahoda** [comment]
On some meeting I mentioned need to teleport assets. IBC ICS20 we use it only reserve transfers. So we would have several stages of workaround may be until reach final solution.

**Comment by kkast** [comment]
this is their tests for native PICA. fot test wise it is native. https://github.com/notional-labs/composable-centauri/blob/main/x/transfermiddleware/relay_test.go#L15

@kollegian when you test pica transfer we can close this ticket

**Comment by josietyleung** [comment]
closing as done
