### ISSUE TITLE
Add in link to direct users to Ping.pub for Banksy PICA's staking + governance 

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/composable#3366]
**Why**
Banky will have its own validator set, staking and governance mechanism. As there existing platforms that provide staking + governance services, we don't need to build this ourselves 

**What**
On Centauri FE, add in a link to Ping.pub where users can stake PICA and vote on Banksy's governance proposals 
https://ping.pub/Composable/staking

**Comment by itsbobbyzz** [comment]
Suggestion that we'll just add it to the header to link https://app.trustless.zone/ to https://ping.pub/Composable

**Comment by josietyleung** [comment]
closing as done
