### ISSUE TITLE
Update transfer extrinsic on UI after Kusama upgrade to xcm v3

### ISSUE THREAD

**Issue by itsbobbyzz** [ComposableFi/composable#3381]
The original task was raised by Yasin at [PICA-327 ](https://app.clickup.com/t/20465559/PICA-327) and has been linked to https://github.com/ComposableFi/composable/issues/3374 

Summary:  After Kusama upgrade to XCM v3 the transfer extrinsic from Kusama to Picasso and Statemine to Picasso should be updated. 

`Example call from Kusama to Picasso: `https: //polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.ibp.network%2Fkusama#/extrinsics/decode/0x89028400cc0877a7643661309c066d45bf39cbdf40dd6176feab75d15a558858596d69590162be8e35daec2256ef1625120517f7302290a11cb9031d3f316d2132178e420e6cd612c2517d8850d73dbe3af06c4ac8841adefd235d0e94bb190f20a7c7b28cc502a4006302010001009d200100010100cc0877a7643661309c066d45bf39cbdf40dd6176feab75d15a558858596d695901040000000002286bee00000000

`Example call from statemine to Picasso: `https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fstatemine.api.onfinality.io%2Fpublic-ws#/extrinsics/decode/0x9d028400cc0877a7643661309c066d45bf39cbdf40dd6176feab75d15a558858596d6959011469ecc4c3a209a8d3a6c7c150c4008eba64de8b6e3cf4625646bf45d34f4028ac31114012329dea9d9fadde13e4a285ceffada0d7d8b4f10e032bbda09e438444007400001f08010101009d200100010100cc0877a7643661309c066d45bf39cbdf40dd6176feab75d15a558858596d69590104000002043205011f00419c0000000000

![2023-04-10_12-39.png](https://images.zenhubusercontent.com/642d9c59b5b052bf0aa0fde0/d91bfac0-4f1b-46a1-8e47-b188ed2195b7)

![2023-04-10_12-45.png](https://images.zenhubusercontent.com/642d9c59b5b052bf0aa0fde0/967f50c5-8446-4a93-853f-388773450dcf)

**Comment by dzmitry-lahoda** [comment]
was it done?

**Comment by dzmitry-lahoda** [comment]
Seems UI we are on to works with V3. So closing for now.
