### ISSUE TITLE
Substitute assets with AssetsTransactorRouter

### ISSUE THREAD

**Issue by itsbobbyzz** [ComposableFi/composable#3384]
Whilst Kostya was performing [PICA-312 ](https://app.clickup.com/t/20465559/PICA-312) he identified in addition we have a router: AssetsTransactorRouter. This router needs to substitute assets pallet currently in picasso and composable. it needs to be added to chain's pallets Configs instead of assets, which will need testing pallets where we will substitute assets to AssetsTransactoRouter.

This is the placeholder task to ensure we complete this and test this.

Kostya Kastsevich commented
Mar 28 at 4:10 pm
this needs to be done for composable and picasso, it can be a part of getting rid of hardcoded assets code. this will require testing other pallets that currently use old assets pallet but will need to use assets-transactor-router. without assets-transactor-router the system is still in between

**Comment by dzmitry-lahoda** [comment]
Closing. AssetsTransactorRouter to be deleted . cc @kkast
