### ISSUE TITLE
Update decimals for dot in assets registry 

### ISSUE THREAD

**Issue by itsbobbyzz** [ComposableFi/composable#3385]
Kostya has identified that currently the assets registry on composable is set to 12 decimals, and should be changed to 10 on chain. 

Maybe same for ibcDOT on picasso, assets registry also has 12 instead of 10 on chain

**Comment by kkast** [comment]
done on both composable and Picasso

**Comment by dzmitry-lahoda** [comment]
@kkast it it done?

**Comment by josietyleung** [comment]
@kkast believe this is done so closing
