### ISSUE TITLE
fix list_assets rpc

### ISSUE THREAD

**Issue by itsbobbyzz** [ComposableFi/composable#3386]
Currently list_assets rpc still uses hardcoded list of CurrencyIds, 

- [ ] need to use keys from ExistentialDeposit storage map of AssetsRegistry: assets_registry::ExistentialDeposit::<Runtime>::iter_keys().collect::<Vec<CurrencyId>>()
- [ ] include all assets in the asset-registry

**Comment by dzmitry-lahoda** [comment]
was it done?

**Comment by dzmitry-lahoda** [comment]
assuming fixed or not used by FE
