### ISSUE TITLE
Introduce multisig.rs to the Composable Run time

### ISSUE THREAD

**Issue by itsbobbyzz** [ComposableFi/composable#3392]
**Summary**

When trying to add treasury multisig to Composable, we realised that the multisig pallet is not within Composable Run time.
<img width="1509" alt="Screenshot 2023-04-12 at 14 22 06" src="https://user-images.githubusercontent.com/88450750/231479953-9a0491f6-de3c-44ac-9366-bd97a9cdf424.png">

**Action**

Add multisig pallet to Composable run time, and merge and schedule for a run time upgrade.

**Comment by kkast** [comment]
https://github.com/ComposableFi/composable/pull/3394
