### ISSUE TITLE
Asset Registry - Permissionless & Readable 

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/composable#3401]
**Why**
Any Cosmos chain can open up channel to Banksy, so we need to let them register their asset on our Picasso & Composable asset registry so they can transfer asset over to Dotsama via Banksy 

**How**
Details in this doc https://docs.google.com/document/u/1/d/1gz_edZiRt0Y0345oLR_EuzYTg6EX692xppn8piA2msU/edit#heading=h.5ncffus5qpov

**Comment by blasrodri** [comment]
@josietyleung who's responsible for these? can we map them to people/teams?

**Comment by dzmitry-lahoda** [comment]
please ensure we aligned with provider of indexing for substrate. we are on polcaholic target now.

**Comment by dzmitry-lahoda** [comment]
final target may be.
1. root AR in Picasso. Gov on Picasso send XCVM to sync ARs on Composable and Banksy.
2. AR is added wrapped with NR(network registry), like it is required by XCVM.
3. export is done to cosmos/polkadot git based ARs manually (on alert of gov added).

**Comment by dzmitry-lahoda** [comment]
4. OpenGov can initiate any changes on any asset using Assets track.
5. Specific accounts can manage limited number of Asset propeties (Admins, can be multisigs).

**Comment by dzmitry-lahoda** [comment]
Quesitons are:
1. What we can do without XC transactions. So handle Assets List spreadsheet in sync. 
2. What requirements to make pemissionless. Step by step. As much as possible without risk.
3. How to handle teleports to banksy. There is other task about teleports out there.

**Comment by dzmitry-lahoda** [comment]
@kkast please spec out what we have discussed so we aligned on what we will get.

**Comment by dzmitry-lahoda** [comment]
@josietyleung was referecne doc update according our dicussions? we cannot align on old doc. i doubt we can progress until that is well defined on half baked proposal.

**Comment by itsbobbyzz** [comment]
@dzmitry-lahoda @kkast I have updated the doc [https://docs.google.com/document/d/1gz_edZiRt0Y0345oLR_EuzYTg6EX692xppn8piA2msU/edit#heading=h.4ty0p0h6d3oq](url) with the relevant discussion on non sufficient assets for your review and to incorporate into the solution.

**Comment by kkast** [comment]
@dzmitry-lahoda i have a quesiton about adding network id to the asset id. to migrate all existing tokens for all accounts with current ids is a heavy operation. do you know if it is ok to run such an operation during storage migration?

**Comment by dzmitry-lahoda** [comment]
search migration guide from parity. they describe how to do it. also may look into parity pallets assets or balances codebase, if they did some big migrations.

**Comment by kkast** [comment]
3 steps to merge this:
1) add network id
2) migrate assets
3) nonsufficient assets
4) cosmwasm assets
5) precompile for cosmwasm

**Comment by dzmitry-lahoda** [comment]
This was closed by bot 

https://github.com/ComposableFi/composable/blob/0f50340d1a214085a38fa31314d3b0b4dc89042d/.github/workflows/maintainance.yaml#L24

It considers issue without any updates for 16 days stale, and closes after 4 days. So issue without 20 days of comments or status changes (or other changes i think) is closed. Values can be changed. It was mostly to clean all stale pr/branches/issues. So can set other values for issues.

**Comment by dzmitry-lahoda** [comment]
```yaml
          stale-issue-message: 'stale-issue'
          close-issue-message: 'close-issue'
          days-before-issue-stale: 16
          days-before-issue-close: 4
          exempt-issue-labels: ''
          only-labels: ''          
          exempt-issue-assignees: ''                 
```

so can filter out some labels, or assigned people.

**Comment by dzmitry-lahoda** [comment]
sorry for inconvenience

**Comment by dzmitry-lahoda** [comment]
btw, it would first of its kind known in Substrate

**Comment by dzmitry-lahoda** [comment]
when bridges create assets automatially

**Comment by josietyleung** [comment]
moving back to backlog as an item to handle prior to eth bridge. as most of the cosmos assets have been added already to AR
