### ISSUE TITLE
CosmWasm VM: Address Halborn audit report 

### ISSUE THREAD

**Issue by itsbobbyzz** [ComposableFi/composable#3403]
This task relates to the Halborn audit report of the Cosmwasm pallet and specifically the medium issue Hal-01 per page 10 of the report. 

3.1 (HAL-01) INSTANTIATE CALL
MISSING ZERO CHECK - MEDIUM
Description:
The gas parameter in the instantiate function of the code lacks validation,
which means that it can accept a value of zero (0) for gas. This can
potentially lead to an undefined behavior, where an attacker can deploy a
contract with no gas limit, causing the contract to consume an excessive
amount of resources and exhaust the Virtual Machine resources, leading
to unexpected behavior inside the Virtual Machine.

**Comment by josietyleung** [comment]
@dzmitry-lahoda do you know if this done already? thanks

**Comment by dzmitry-lahoda** [comment]
not done

**Comment by itsbobbyzz** [comment]
[Composable_Finance_CosmWasm_Pallet_Substrate_Pallet_Security_Audit (1) (1).pdf](https://github.com/ComposableFi/composable/files/12039079/Composable_Finance_CosmWasm_Pallet_Substrate_Pallet_Security_Audit.1.1.pdf)

**Comment by dzmitry-lahoda** [comment]
done by document from Mina86. Reopen if needed
