### ISSUE TITLE
Fix Picasso Rococo faucet 

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/composable#3417]
**Existing** 
faucet for picasso rococo https://matrix.to/#/#picasso-rococo-faucet:matrix.org is showing `1010: Invalid Transaction: Transaction has a bad signature ` when requesting token

**Expected** 
Faucet should be sending 2000PICA for each request, instead of throwing error

**Comment by julio-jimenez** [comment]
Updated faucet to latest version. Issue is not present in latest transaction.
