### ISSUE TITLE
Add slashing for passive oracles

### ISSUE THREAD

**Issue by kkast** [ComposableFi/composable#3428]
If oracles are not submitting price regularly, it can lead to price inaccuracies.  PrePrice lives for T::StalePrice amount of blocks in queue, after that submitted price is removed. One oracle cant submit price for the same asset if it is in PrePrice queue.  Thus, oracles must submit price for each asset at least every T::StalePrice blocks.

suggestion: slash oracles for assets which they dont submit price for T::StalePrice + 4 blocks.

**Comment by kkast** [comment]
we postpone this

**Comment by blasrodri** [comment]
yes, for next month
