### ISSUE TITLE
Use `composable-testfast-node` in `devnet-centauri`

### ISSUE THREAD

**Issue by obsessed-cake** [ComposableFi/composable#3438]
This needs to do `centauri` tests faster.

**Comment by blasrodri** [comment]
Sorry @obsessed-cake if this came up as a priority, but it's not. It's more like a nice to have. But for now, we would rather focus on putting CW pallet in prod, and having the bridge operationally. Then we can tackle this optimizations. I apologize if it wasn't clear from my side.

**Comment by dzmitry-lahoda** [comment]
@josietyleung should I enable prio tags so people aware of items prios?

**Comment by dzmitry-lahoda** [comment]
Speed up of testing will happen if 1. enable warp (snapshot/fork) like run of compsable runtime enabled. 2. self sealing enabled (also some rust code base to look at how other chains doing it) 3. and sure use testfast everywhere (i used it in devnet).

**Comment by josietyleung** [comment]
this issue has been placed in the Icebox column, which means it's one of the lowest priority issues and shouldn't be addressed at all. 
in terms of priority: 
- 'In Progress' should be the ones we are working on 
- 'Weekly Backlog' columns are the next ones we should work on once 'In Progress' are done https://github.com/ComposableFi/Private-Issues-#workspaces/engineering-641c38470b9cb9bba40da722/board 

Issues in 'Product Backlog' or 'Icebox' are for the future :)

**Comment by dzmitry-lahoda** [comment]
Imho if things are not considered to be done they are not subject for issue for execution. Until issue is aligned other means it should not be on board.

**Comment by dzmitry-lahoda** [comment]
done
