### ISSUE TITLE
Dex Router

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/composable#3445]
**Why** 
We are currently using Pablo::spot() to fetch flat fee pricing, which won't work for assets that don't have USDT pairing 

**How**
1. Use dex-router::spot() instead 
2. Update the Pablo swap page so all assets will show up as a swap option 

Slack thread https://composablefinance.slack.com/archives/C02JDCUNLLV/p1683588195962259

**Comment by kkast** [comment]
@josietyleung if there are multiple paths to usdt, which one should we choose? 1inch offers one with the best price and liquidity

**Comment by dzmitry-lahoda** [comment]
yeah, idea that stale just notifs to either unstale or it will be removed. afaik best policy, given we can search closed items, is to keep only couple of months of execution open, i assume this task is planned.

**Comment by josietyleung** [comment]
Yeh it's planned to scope and then we'll decide. It's in Kostya to do list
