### ISSUE TITLE
Update IBC Pallet to use Asset Transaction Router instead of Assets Pallet 

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/composable#3474]
**Why** 
We have added in a asset transaction router, but the ibc pallet is still using assets pallet 

**How** 
Update IBC pallet to use asset transaction router instead of assets pallet

**Comment by dzmitry-lahoda** [comment]
what for it?

**Comment by kkast** [comment]
https://github.com/ComposableFi/composable/pull/3740

**Comment by dzmitry-lahoda** [comment]
AssetTransactionRouter pallet not to be used, nor new pallet added
