### ISSUE TITLE
Disable CTA if user's entered amount is less than flat fee 

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/composable#3502]
**Why** 
We will be introducing flat fee for Centauri where we charge $10 of the asset transferred. If the user sends any amount less than $10, then the user will receive nothing as it all goes the flat fee.

**How** 
1. We should disable the CTA if the entered amount of a flat fee asset is less than $10 and show text explaining to users. 
2. ' The amount you are looking to transfer is lower than the fee required ($10). Please increase your transfer amount and try again' 
3. The $10 shouldn't be hardcoded.

**Comment by nahyunbak** [comment]
This issue is moved to https://github.com/ComposableFi/composable-fe/issues/171
