### ISSUE TITLE
Ensure Max amounts can be selected on centauri for bridge transfers

### ISSUE THREAD

**Issue by kollegian** [ComposableFi/composable#3518]
Currently, when max amounts selected for ibc amounts: 
1- Initially transfer button is disabled when max selected. 
![image](https://user-images.githubusercontent.com/64729564/234964862-2be71aab-4224-4a31-b04c-f59858034608.png)
2- When manually entered the available balance, users see this error which shouldnt be the case because protocol fee is charged on destination chain. So unless payment asset, users should be able to send their balances fully with keep alive setting).
![image](https://user-images.githubusercontent.com/64729564/234965707-d3d1738c-c110-4f08-b35d-0454d9b2f14a.png)
2- The max amount reduces some amount from available max balance of user. And changing keep alive parameter on setting doesnt change this amount. 
![image](https://user-images.githubusercontent.com/64729564/234965112-7fa8a06c-b537-40b2-8f13-16cc0fba0916.png)
3- After manually changing the amount and then clicking max enables transfer button. 
![image](https://user-images.githubusercontent.com/64729564/234965293-acd6a8c6-8835-435e-b29d-01bc2640ec2a.png)
But gets this error.

**Comment by nahyunbak** [comment]
This issue is moved to https://github.com/ComposableFi/composable-fe/issues/173
