### ISSUE TITLE
Display a loader for payment asset change tx on centauri

### ISSUE THREAD

**Issue by kollegian** [ComposableFi/composable#3519]
When users select to change payment asset on centauri, after signing the tx, users dont see a loader or an info message that says the tx is being sent. Therefore this can create a confusion if the tx is sent or not. After signing the tx users see this. 
![image](https://user-images.githubusercontent.com/64729564/234966496-d952dd10-e470-420e-a976-2522a11e59fb.png)

**Comment by nahyunbak** [comment]
This issue is moved to https://github.com/ComposableFi/composable-fe/issues/170
