### ISSUE TITLE
Disable any payment asset option on composable other than DOT on centauri

### ISSUE THREAD

**Issue by kollegian** [ComposableFi/composable#3520]
On centauri, on composable we expect users to pay with dot but on payment asset change option users can select ksm as well as dot. Here users are displayed with all token options they have on composable. 
![image](https://user-images.githubusercontent.com/64729564/234967280-36a703ee-9c79-4c50-b3e4-9445474c349d.png)
But when users select ksm or any other token than DOT, this error message is displayed. Therefore we can disable all other token options but DOT here. 
![image](https://user-images.githubusercontent.com/64729564/234967476-6b96e7e4-8ba5-4e0b-b991-d0fc2153d423.png)

**Comment by nahyunbak** [comment]
This issue is moved to https://github.com/ComposableFi/composable-fe/issues/175
