### ISSUE TITLE
Update listAssets rpc

### ISSUE THREAD

**Issue by kkast** [ComposableFi/composable#3521]
rn it still has hardcoded assets just in case, remove hardcoded assets from this rpc on composable and picasso and make sure that nothing break on FE side

**Comment by josietyleung** [comment]
@kkast do you mean subsquid?

**Comment by kkast** [comment]
https://github.com/ComposableFi/composable/pull/3739

**Comment by dzmitry-lahoda** [comment]
@kkast is id done?

**Comment by josietyleung** [comment]
closing as done
