### ISSUE TITLE
stop using hardcoded assets on the bridge

### ISSUE THREAD

**Issue by kkast** [ComposableFi/composable#3522]
Dzmitry said we are still using hardcoded ids for the bridge. Lets use AssetsRegistry via AssetsTransactorRouter instead

hardcoded asset in runtime/primitives/src/currency.rs

**Comment by dzmitry-lahoda** [comment]
@RustNinja seems intorduced more hardcoded  into framing. I will not be able to approve such pre release to release.

**Comment by kkast** [comment]
we use assets from AssetsRegistry. we use hardcoded assets just for ids, so i think we can close this one

**Comment by josietyleung** [comment]
@kkast is this done/

**Comment by dzmitry-lahoda** [comment]
no use of AssetsTransactorRouter.  genesis devnet uses still hardcodes btw. but not prod

**Comment by dzmitry-lahoda** [comment]
prio tbh to remove CurrencyFactory and AssetsTransactorRouter.
