### ISSUE TITLE
Subsquid Volume Display in DOT-USDT pool, treats USDT as 10 decimals

### ISSUE THREAD

**Issue by kollegian** [ComposableFi/composable#3538]

**Comment by kollegian** [comment]
**Overview** When users do txs on ODT-uSDT pool, the volume amount for USDT is displayed on pablo app in 10 decimals while it should be 6 decimals. 

**STR**
1- User does a swap for 2 usdt for DOT
![image](https://user-images.githubusercontent.com/64729564/235459323-82f0d0f5-0247-4836-8fd4-15f1fd4f9f61.png)

2- The volume should display 2$ in daily data but the volume displays 0.0002 USD. 
![image](https://user-images.githubusercontent.com/64729564/235459405-e5b9d1ab-bc7b-4e09-a016-5c9fd299ccee.png)

**Comment by nahyunbak** [comment]
This issue is moved to https://github.com/ComposableFi/composable-fe/issues/176
