### ISSUE TITLE
Pool Volume for Weekly Data doesn't include only single asset days in calculations 

### ISSUE THREAD

**Issue by kollegian** [ComposableFi/composable#3539]

**Comment by kollegian** [comment]
**Overview**
On Pablo, we are displaying weekly volume for pools on specific pool page. However, this volume data is not including the days that have only one single volume. 
![image](https://user-images.githubusercontent.com/64729564/235460751-068dc13c-c29a-4d34-a294-a5362a750118.png)
![image](https://user-images.githubusercontent.com/64729564/235460811-9dc5bd84-1fd3-453f-91ae-dd25573d7b5e.png)

If one to add all amounts listed in subsquid, the amount should be 572, but displayed amount on pool page is 432. The single asset day on DOT for the pool, is left unincluded.

**Comment by nahyunbak** [comment]
This issue is moved to https://github.com/ComposableFi/composable-fe/issues/172
