### ISSUE TITLE
Rename Volume Data on Specific Pool page to Week and Month respectively

### ISSUE THREAD

**Issue by kollegian** [ComposableFi/composable#3540]

**Comment by kollegian** [comment]
On Specific Pool Page, the volume for pool is displayed as D-W-All but in reality what is displayed there is Week-Month and All.
![image](https://user-images.githubusercontent.com/64729564/235461506-f08dd215-36ca-425b-bc0f-74e0554b645b.png)

 Also while calculating the weekly volume we can include the daily volume on top of weekly and monthly values. For instance here daily volume is higher than the weekly and monthly volume. So adding the daily volume on top of these values might be useful. 
![image](https://user-images.githubusercontent.com/64729564/235461626-bf7aaaff-a316-4a4c-bbbe-57bb3c270c08.png)
On pool page: 
![image](https://user-images.githubusercontent.com/64729564/235461699-ee4f8c9b-7fe1-43a6-b776-b6c1b5b0c445.png)

**Comment by nahyunbak** [comment]
This issue is moved to https://github.com/ComposableFi/composable-fe/issues/169
