### ISSUE TITLE
On Centauri, changing receiving wallet address, changes the sender as well

### ISSUE THREAD

**Issue by kollegian** [ComposableFi/composable#3541]

**Comment by kollegian** [comment]
**Overview**
On Centauri, we are giving users to option to specify the receiving address. Currently, we are only allowing users to send funds to one of their accounts on picasso or composable. But when users select another of their accounts as receiver for transfers, the sender also changes to this address. 
Here; sender has the funds and the receiver is the same address
![image](https://user-images.githubusercontent.com/64729564/235463259-7df189b7-e551-44e5-8a39-2c4bc4bfd413.png)
But when receiver is changed, the sender also changes, displays no balance and changes the connected account. 
![image](https://user-images.githubusercontent.com/64729564/235463627-a787f2b0-699b-4088-90ba-098d119b2ec7.png)

**Comment by nahyunbak** [comment]
https://github.com/ComposableFi/composable-fe/issues/166
This issue is moved to Composable-fe repo
