### ISSUE TITLE
Pablo - On Add Liquidity, when users select to use token inputs instead of dollar value inputs, the sent amount slightly differs from what is displayed to the users

### ISSUE THREAD

**Issue by kollegian** [ComposableFi/composable#3542]

**Comment by kollegian** [comment]
**Overview**
When users select to use token inputs instead of dollar value on pablo, and select the amount to add liquidity, the actual amount sent on chain slightly differs from what is selected by the user. 
![preTx](https://user-images.githubusercontent.com/64729564/235465578-6abb121b-36f2-418e-8f0a-6d5e955db90d.png)
![actualTx](https://user-images.githubusercontent.com/64729564/235465589-3946c4aa-eaf0-42ce-8343-89e02b84d93b.png)

**Comment by nahyunbak** [comment]
https://github.com/ComposableFi/composable-fe/issues/165
Opened issue at composable-fe repository
