### ISSUE TITLE
Wallet Breakdown on Centauri doesn't display lp tokens on DOT pools

### ISSUE THREAD

**Issue by kollegian** [ComposableFi/composable#3543]

**Comment by kollegian** [comment]
**Overview**
On centauri, balance display on wallet tab, doesn't display newly created DOT pools lp token balance. 
![image](https://user-images.githubusercontent.com/64729564/235484693-fce02423-95b9-4d5d-9112-383fbd19f691.png)

**Comment by bengalmozzi** [comment]
Currently, we are using the tempAssets that were pre-defined in the configuration. We need to change it to be the same as Pablo's
