### ISSUE TITLE
Testing XCM Integration with Moonriver/Moonbeam

### ISSUE THREAD

**Issue by JafarAz** [ComposableFi/composable#3553]
[Moonriver/Moonbeam XCM Integration docs](https://docs.moonbeam.network/builders/interoperability/xcm/xc-integration/#moonbase-alpha-xcm)

[Further docs](https://docs.moonbeam.network/learn/platform/networks/moonbase/) related to Moonbase Testnet.

The first step for a Moonriver/Moonbeam XCM integration is to integrate with the Moonbase Alpha TestNet, through the Alphanet relay chain. Then a Moonriver integration must be completed before proceeding with Moonbeam (if applicable).

Once hooked up with the Moonbase Testnet, we will test the Picasso <> Moonriver XCM integration first as outlined in the docs. Following the completion of this test, we can test the Composable <> Moonbeam XCM integration.

After this testing process has been completed, I will post a governance proposal on the Moonriver/Moonbeam forum as required.

**Comment by JafarAz** [comment]
[Moonriver/Moonbeam XCM Integration docs](https://docs.moonbeam.network/builders/interoperability/xcm/xc-integration/#moonbase-alpha-xcm)

[Further docs](https://docs.moonbeam.network/learn/platform/networks/moonbase/) related to Moonbase Testnet.

The first step for a Moonriver/Moonbeam XCM integration is to integrate with the Moonbase Alpha TestNet, through the Alphanet relay chain. Then a Moonriver integration must be completed before proceeding with Moonbeam (if applicable).

Once hooked up with the Moonbase Testnet, we will test the Picasso <> Moonriver XCM integration first as outlined in the docs. Following the completion of this test, we can test the Composable <> Moonbeam XCM integration.

After this testing process has been completed, I will post a governance proposal on the Moonriver/Moonbeam forum as required.

**Comment by dzmitry-lahoda** [comment]
I sure want to sell them DevNet testing, we(I) may dicuss with them imho.

**Comment by dzmitry-lahoda** [comment]
@JafarAz 
```
To sync a node, you can use the [Alphanet relay chain specs](https://drive.google.com/drive/folders/1JVyj518T8a77xKXOBgcBe77EEsjnSFFO) (note: the relay chain is Westend based, and will probably take 1 day to sync).
```
Westend... We do not have Composable on Westend yet.

**Comment by dzmitry-lahoda** [comment]
I am talking about docs they have. They tell rococo and westend first as I read these correctly.

**Comment by JafarAz** [comment]
Why would we need Composable on Westend? From what I understand, we are connecting our mainnet chains with their testnet

**Comment by dzmitry-lahoda** [comment]
I do not feel good about that for various reasons.

**Comment by JafarAz** [comment]
https://github.com/ComposableFi/Private-Issues-/issues/58

**Comment by dzmitry-lahoda** [comment]
Closing as not work on this repo here. Please track in SRE or PrivateIssues
