### ISSUE TITLE
LP Staking Pallet Events displays token decimals multiplied with 18

### ISSUE THREAD

**Issue by kollegian** [ComposableFi/composable#3555]

**Comment by kollegian** [comment]
**Overview**
On some and some storage query on farming pallet returns token decimals multiplied by 18 decimals. 
![multipliedEvent](https://user-images.githubusercontent.com/64729564/236129246-6b589e10-1c24-4fa3-b184-9980b323d0f9.png)
![storageDecimals](https://user-images.githubusercontent.com/64729564/236129288-999ba09d-7be6-42d5-b4fd-d48ee16c0076.png)

**Comment by josietyleung** [comment]
agreed with nikita that this is expected behaviour
