### ISSUE TITLE
Opening HRMP channel between Composable <> Statemint

### ISSUE THREAD

**Issue by JafarAz** [ComposableFi/composable#3558]
Statemint's integration is different to other parachains because it is one of the only system parachains (common good parachain).

Opening an HRMP channel with a system parachain requires a referendum. (Jafar will post the proposal on the Polkadot forums).

Para id for Statemint: 1000

Proposals should generally be a batch_all call containing:

1. A force_transfer of the channel deposit from the Treasury to the System parachain's sovereign account. Remember that a bi-direction channel is two channels so will need double the amount.
2. A force_open_hrmp_channel from your chain to the system chain.
3. A force_open_hrmp_channel from the system chain to your chain. 

[_Source_](https://wiki.polkadot.network/docs/build-hrmp-channels#opening-hrmp-channels-with-system-parachains)

The proposal needs to include the `Encoded call data` and `Proposal Hash`.

Once a statemint channel is opened, the FE team will need to support Statemint transfers on app.trustless.zone to allow USDT transfers between Statemint and Composable.

**Comment by dzmitry-lahoda** [comment]
I will handle this.

**Comment by dzmitry-lahoda** [comment]
please track work on PrivateIssues or SRE repo, there is nothing to do in Composable repo until request for DevNet arrives.
