### ISSUE TITLE
Opening HRMP channels with BiFrost

### ISSUE THREAD

**Issue by JafarAz** [ComposableFi/composable#3560]
BiFrost has both a Kusama and Polkadot parachain.

A single-direction channel is currently open for Picasso --> BiFrost Kusama. I believe the channel request has been sent to BiFrost for a BiFrost Kusama --> Picasso channel. 

The remaining channels that need to be opened are bi-directional channels between BiFrost Polkadot and Composable.

**Comment by dzmitry-lahoda** [comment]
```
Tyrone | Bifrost
@dzmitry_lahoda we've sent channel request to Composable on Polkadot, wait for your accept and request back
https://bifrost.subscan.io/xcm_channel/2030-2019
[bifrost.subscan.io](https://bifrost.subscan.io/xcm_channel/2030-2019)
Subscan | Aggregate Substrate ecological network high-precision Web3 explorer

Subscan | Substrate ecological explorer: Search, analyze, and visualize blockchain that occurs on Substrate based network (Polkadot, Kusama, Moonbeam, Acala, Darwinia), s...
```

**Comment by dzmitry-lahoda** [comment]
@RustNinja may you help to form relevant XCM messages on our side for execution according  our current governance structure on Composable to open channels? When messages are formed please attach these here and reassign task to me (so I can kick of governance stuff). Thank you

**Comment by JafarAz** [comment]
For Picasso <> BiFrost Kusama I see a request has been sent to open a channel https://picasso.subscan.io/xcm_channel/2001-2087

Are we pending to accept the request or the BiFrost team?
