### ISSUE TITLE
Make pallet `weight` take message size into account.

### ISSUE THREAD

**Issue by krl** [ComposableFi/composable#3576]
Possible issue discovered by @dzmitry-lahoda 

When calling `instantiate` and `execute` (possibly others), the size of the message does not contribute to the weight of the call. Since the message size can be set to several hundred kilobytes, this is DDOS risk.

**Comment by josietyleung** [comment]
closing as merged

**Comment by dzmitry-lahoda** [comment]
it was never fixed. we cannot make CW permissionless
