### ISSUE TITLE
Build adaptor for Pablo to interact with CW 

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/composable#3605]
**Why** 
Pablo's current integration is done for iBC pallet only and not CW, so it can't interact with CW txs 

**How** 
Build an adaptor to add in the integration for CW pallet 

Slack thread here for more info https://composablefinance.slack.com/archives/C053UJMGT1R/p1683067085475649

**Comment by dzmitry-lahoda** [comment]
I have done it and it was merged. So people started to ask more. Like generating json schema and more precompiles for other things.

**Comment by dzmitry-lahoda** [comment]
cc @kkast

**Comment by dzmitry-lahoda** [comment]
Fixed by me.
