### ISSUE TITLE
IBC rate limiter in 7.10023.1 is garbage

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/composable#3611]
impl Ics20RateLimiter for ConstantAny {
	fn allow(
		msg: &pallet_ibc::ics20::Ics20TransferMsg,
		_flow_type: pallet_ibc::ics20::FlowType,
	) -> Result<(), ()> {
		let pica_denom =
			<<Runtime as pallet_ibc::Config>::IbcDenomToAssetIdConversion as DenomToAssetId<
				Runtime,
			>>::from_asset_id_to_denom(CurrencyId::PICA);

		let limit = match msg.token.denom.to_string().as_str() {
			denom if Some(denom) == pica_denom.as_deref() => 500_000,
			_ => 10_000,
		};
		if msg.token.amount.as_u256() <= ::ibc::bigint::U256::from(limit * 10_u64.pow(12)) {
			return Ok(())
		}
		Err(())
	}
}

**Comment by dzmitry-lahoda** [comment]
rate limiter does not work as advertised

for USDT it is 10^9 .
for PICA is is 10^4.
for DOT it is 10^6.

cc @josietyleung

**Comment by josietyleung** [comment]
fixed in https://github.com/ComposableFi/composable/pull/3620
