### ISSUE TITLE
User staked balance displays wrong percentage

### ISSUE THREAD

**Issue by kollegian** [ComposableFi/composable#3619]
On pablo, after user stake their balance the displayed staked amount is wrong. 

STR: 
1- User gets lp tokens
2- Selects max and stakes all their lp tokens
3- On pool page, users should see the staked amount is 100%
![2023-05-18_13-57](https://github.com/ComposableFi/composable/assets/64729564/022144aa-b1a9-487a-9b9a-cbc1a17bdc1b)
![stakedamountwrong](https://github.com/ComposableFi/composable/assets/64729564/4edaa266-cd40-49b1-8531-ef8bdef3fd7b)

**Comment by dzmitry-lahoda** [comment]
FE issue. FE removed. closign.
