### ISSUE TITLE
Speed up integration test 

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/composable#3629]

**Comment by RustNinja** [comment]
Need to update tests because tests fail when block time is 6 sec.
Actually this issue relegated to centauri

**Comment by RustNinja** [comment]
> 

yes. need to update centauri integration tests to be on the same page with a new block time after fix(block time for parachains)

**Comment by dzmitry-lahoda** [comment]
not sure what it is.

if fix on centauri - make task on them.
if need to change block time - when you change block time, need handle block time on relay, and so forth. 

i am 100% for block time reduction, but need than reduce all parameters everywehre and in assets hub, etc. too big task.

there are better ways to speed up devnet for example, or make hyperspace faster, or faster testnet. let create more concrete tasks for that.
