### ISSUE TITLE
IBC Pica transfers over 10K pica is not being received by the receiving chain

### ISSUE THREAD

**Issue by kollegian** [ComposableFi/composable#3631]
For Pica, ibc limit is 500K for both chains. However, transfers over 10K pica is not being received by the receiver chains. Tried on both picasso => composable and composable => picasso. 
![image.png](https://images.zenhubusercontent.com/643d5cdebf86a75babbab933/a18ea5e4-59c8-4d9b-8bf1-58853f22288b)

**Comment by blasrodri** [comment]
Do you see any logs with errors?

**Comment by kkast** [comment]
@kollegian is this fixed with the latest release?

**Comment by kollegian** [comment]
Yes sir, this is fixed now. Moving this to done.
