### ISSUE TITLE
Add Pablo Farms to Vfat

### ISSUE THREAD

**Issue by JafarAz** [ComposableFi/composable#3648]
https://vfat.tools/ is a farming tool used in the DeFi space to get a holistic view of different farms available. An existing composable farm exists on the website, which we should delete since the strategies are now deprecated.

The task requires us to add Pablo's pools, similar to this [example PR](https://github.com/vfat-tools/vfat-tools/pull/2389), it is the entire code for displaying a page (html + js) and involves adding APIs to query the APRs for the pools.

Get started here: https://github.com/vfat-tools/vfat-tools

**Comment by JafarAz** [comment]
https://vfat.tools/ is a farming tool used in the DeFi space to get a holistic view of different farms available. An existing composable farm exists on the website, which we should delete since the strategies are now deprecated.

The task requires us to add Pablo's pools, similar to this [example PR](https://github.com/vfat-tools/vfat-tools/pull/2389), it is the entire code for displaying a page (html + js) and involves adding APIs to query the APRs for the pools.

Get started here: https://github.com/vfat-tools/vfat-tools

**Comment by dzmitry-lahoda** [comment]
it is FE task, not this repo task. closing. please open on FE.
