### ISSUE TITLE
Nixify Composable Cosmos Devnet 

### ISSUE THREAD

**Issue by kollegian** [ComposableFi/composable#3670]
Overview
For Local testing and integration, running composable cosmos devnet is needed. Having simple commands to run this infrastructure would be more convenient. 
@dzmitry-lahoda do you already have this at hand?

**Comment by blasrodri** [comment]
@dzmitry-lahoda just to know, when would this be finished? I see you've started working on it :)

**Comment by dzmitry-lahoda** [comment]
I used this config https://composablefinance.slack.com/archives/C02MSA16DCP/p1686589830730029?thread_ts=1686574377.873029&cid=C02MSA16DCP with for sure modificaiton when it does not work.

**Comment by dzmitry-lahoda** [comment]
It loops infinitely with no errors at logs.

**Comment by dzmitry-lahoda** [comment]
Now blocked by fact bridge team does no release in GitHub. So not clear what versions of  of pallet, contract and relay are compatible at same time.

**Comment by dzmitry-lahoda** [comment]
![image](https://github.com/ComposableFi/composable/assets/757125/fe885e03-3c69-4f52-9577-d7e136b2914f)

**Comment by dzmitry-lahoda** [comment]
I takes 10 minutes to start. Hyperspace fails hundreds of time with serde error, but than some how works magically. 
There is no composable for various reasons, I do not support darwin for various reasons, I did not tested any transfers.

Please raise new separate tickets for any of this.

**Comment by dzmitry-lahoda** [comment]
`mkdir /tmp/composable-devnet/hypersapce && nix run .#devnet-xc`
