### ISSUE TITLE
Update Ratios and Locations on Asset Registry for XCM transfers 

### ISSUE THREAD

**Issue by kollegian** [ComposableFi/composable#3682]
**Overview**
When XCM transfers are tried, they are failing with xcmpquefail and tooexpensive errors. 
**The links for bifrost transfers:** 
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbifrost-rpc.dwellir.com#/explorer/query/0x29342c7b8135c93b55ad9ab6e06782aa6c1eef2b40a208429b4111a06502acc6
fail on picasso: 
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpicasso-rpc.dwellir.com#/explorer/query/0xc41e5bbe7f4ddc1879d6d47cf42032e7f881a2522bc355a2f8dba50ba80d564b
**Tinkernet**
block number: 1,937,617	
link: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Finvarch-tinkernet.api.onfinality.io%2Fpublic-ws#/explorer/query/0x189f77c9058ba4e3160774500b9af52a51f26538d7fa9cc3b75a7d518e69cd48
fail: 2,587,955	
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpicasso-rpc.dwellir.com#/explorer/query/0x7a41465fa1f62a571c5cd32b73a8ab0bc0c9a1b8725cfed4331e928e553d5f3d
**shiden**
block no 4,180,218
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fshiden.public.blastapi.io#/explorer/query/0xeb9633193a929e464f057e7d0cb0209095f48a24c1c3cff035606863eee96a80
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpicasso-rpc.dwellir.com#/explorer/query/0x808874f5cc3a9a9082e3a121aeac481144eeba2f090fd79982ea5bda12ed5aae

The communications can be seen here: https://composablefinance.slack.com/archives/C057C6HFKGS/p1686342981860979

**Comment by kkast** [comment]
@kollegian isnt this done?

**Comment by kollegian** [comment]
yes sirs it is done closing now
