### ISSUE TITLE
Update IBC rate limiters for new xcmed assets to Picasso and Composable

### ISSUE THREAD

**Issue by kollegian** [ComposableFi/composable#3711]
Overview: Currently we have predefined rate limiters for ibc assets. For newly added assets, Astar, BNC from Polkadot and VDot we need to define rate limiters. For instance astar has 18 decimals and rate limiter prevents 19 decimals.

**Comment by dzmitry-lahoda** [comment]
yeah, time to do storage for rate limiting as it may go unsustainable like hardcoding

**Comment by kkast** [comment]
https://github.com/ComposableFi/composable/pull/3714/files

**Comment by josietyleung** [comment]
closing as merged
