### ISSUE TITLE
test picasso assets migration

### ISSUE THREAD

**Issue by kkast** [ComposableFi/composable#3762]
picasso migration pr https://github.com/ComposableFi/composable/pull/3761. we need to migrate lp tokesn because their asset_ids dont fit new structure. i tested on chopsticks and it should be good but need second opinion. on chopsticks by some reason old values for old keys stay in storage. i tested in local node and values for old keys are cleaned steps to test it on a local node on main branch 
1) create new lp pool
2) add name, symbol, decimals, ratio, ed to assets_registry of new lp tokens
3) add liquidity and get lp tokens
4) stake some lp tokens
5) accumulate rewards in staking
6) run runtime upgrade(need to increment runtime version)
7) check that all of the values in all storages for pallets changed accordingly: assets_registry, pablo pools, farming pallet, farmingRewards pallet, orml_tokens pallet

next steps: change composable denoms on picasso, update dot assets

current asset id structure: first 8 bytes are palletId (pal_pblo for pablo) , next 8 bytes are nonce
new lp tokens structure: first 4 bytes are network id([0,0,0,0] for picasso, [0,0,0,1] for composable), next 4 bytes index (in picasso config pablo has index 59), next 8 bytes are nonce

**Comment by kkast** [comment]
composable assets old ids -> new ids:
(130, 79228162514264337593543950466)
(1, 79228162514264337593543950337)
(127, 79228162514264337593543950463)
(33, 79228162514264337593543950369)
(2006, 79228162514264337593543952342)
(2, 79228162514264337593543950338)
(2011, 79228162514264337593543952347)
(6, 79228162514264337593543950342)
(4, 79228162514264337593543950340)
(34, 79228162514264337593543950370)

**Comment by kkast** [comment]
for composable also need to check ibc pallet, if there are storages that use tokens

**Comment by kkast** [comment]
Also , for testing Picasso migration we need to check that we can claim newly accumulated rewards, unstable, get tokens back after removing liquidity

**Comment by kkast** [comment]
Also need to check weights for migration

**Comment by dzmitry-lahoda** [comment]
how it is going?

**Comment by josietyleung** [comment]
closing as done
