### ISSUE TITLE
Running Moonbeam parachain

### ISSUE THREAD

**Issue by bostercf** [ComposableFi/composable#3778]
I am unable to run the requested chain using Composable software, so I am using the official moonbeam application with the following steps:
```

sudo mkdir /var/lib/moonbeam-data
sudo chown composable /var/lib/moonbeam-data
wget https://github.com/ComposableFi/composable/raw/moonbase-alpha-parachain/code/parachain/node/src/res/composable-moonbase.json
sed -i 's/relay_chain/relayChain/;s/para_id/paraId/' composable-moonbase.json 

sudo docker run --network="host" -v "/var/lib/moonbeam-data:/data" -v "/tmp/composable-moonbase.json:/composable-moonbase.json" -u $(id -u ${USER}):$(id -g ${USER}) purestake/moonbeam:v0.31.1 --base-path=/data --chain /composable-moonbase.json --name="$(hostname)" --execution wasm --wasm-execution compiled --state-pruning archive --trie-cache-size 0 --db-cache 8192 -- --execution wasm --name="$(hostname)"

```
The application starts up and the relay chain syncs.  I can run two instances of the application and force them to peer by jamming in bootnodes at runtime. However, I cannot create blocks on the parachain side.  My guess is that maybe we need a new genesis file and the Relaychain needs to know about (and approve?) our parachain collators in order for it to work.

**Comment by dzmitry-lahoda** [comment]
@RustNinja we would have done moombeam 2 month ago if just do devnet, it was easy. 2 days max :)

**Comment by dzmitry-lahoda** [comment]
our node can run any json, not need for that json to be here. as not modification need to be done to rust code. closing this, please use and jsons from and to sre repo. 

chainspec can be used and provided from any folder and moonbeam test is not for reuse, unlike devnet could be.

so closing this, please track work on SRE repo, or PrivateIssue.
