### ISSUE TITLE
Run Time Upgrade: release-v9.10000.0 

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/composable#3821]
### Goal: 
1. Add batching (on chain logic) on mainnet, this will let FE start batching integration.
2. flat fee should not included / migration code should be removed

### Progress:
- [x] review required PRs @kkast 
- [x] local testing @NOOB6942069 
- [x] finalise CI to merge @kkast 
- [x] build release candidate (including wasm file) @kkast 
- [x] upgrade + test on chopsticks @NOOB6942069 
- [x] picasso-roccoco: @bostercf 
  - [ ]  node upgrade
  - [ ]  RPC 
  - [x]  runtime upgrade
- [ ] composable: @bostercf 
  - [ ] node upgrade
  - [ ] RPC 
  - [ ]  runtime upgrade
- [ ] picasso-kusama: @bostercf 
  - [ ]  node upgrade
  - [ ] RPC 
  - [ ]  runtime upgrade
- [ ] confirm stability @bostercf 
- [ ] smoke test production @NOOB6942069

**Comment by dzmitry-lahoda** [comment]
This repo does not release FE nor SRE, nor anymore have any docs or builds or release for anythign like that. pleas create issue on these repos or on PrivateIssue. Please keep issues on this repo only for work done in this repo.

as far as i see this repo all work done,

```
 review required PRs @kkast
 local testing @NOOB6942069
 finalise CI to merge @kkast
 build release candidate (including wasm file) @kkast
 upgrade + test on chopsticks @NOOB6942069
```
so closing.
