### ISSUE TITLE
RPC/ Indexer to display user’s funds on XCVM interpreter 

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/composable#3886]
**Why**
For XCVM v0, user can perform a cross chain swap with only the the source ecosystem's wallet. E.g swap DOT on Picasso for CMDX on Osmosis. The swapped asset ie CMDX from another ecosystem will stay in the XCVM contract on Osmosis. 

Details described in User Story 3 + 4 here https://github.com/ComposableFi/Private-Issues-/issues/77

**DoD**
Indexer will need to query the interpreter and display the user's balance held in the smart contract on our Trustless proxy wallet. Per the above example, user should see on our proxy wallet that she has CMDX on Osmosis

**Comment by blasrodri** [comment]
@josietyleung given that we are using pfm and ics20, it should be doable without any extra rpc?

**Comment by josietyleung** [comment]
You're right. This was written before pfm handled auto rollback 😁 
Lemme update it, we will need to display user's funds on XCVM interprete. Except it's not for stuck funds, but for the scenario where user does cross chain swap AND only have one wallet AND keeps swapped asset is opposite ecosystem, thus funds stay in interpreter.

**Comment by dzmitry-lahoda** [comment]
First, there is no async packet handling in Picasso, so in Picasso it will not handle rollback. Nor multi hop transfer no XCVM. So we have problem 1. multi hop transfer can stuck.


Second, on Cosmos, rollback will happen iff we failed to swap. If we success swap and use WASM termination, then fail may not deliver message 2. funds will stuck, so with rollbacks it will be more rare. user can send next XCVM program (to be given to FE team as example) which can move funds. 
If we use other protocols (there are +1 for transfer and +2 for swap), handling will be different, with rollbacks of some kinds, but same applies - restore program can be sent.

If we talk about Picasso, picasso IBC+CW impl is blackhole in terms of API/state/readability. Technically state can be obtained, but requires expretise in Substrate and IBC and CW to decode it, which I guess not what FE has one.

**Comment by dzmitry-lahoda** [comment]
For Cosmos we do and going to do as per scenarios and some planned tasks.

**Comment by dzmitry-lahoda** [comment]
wrote to slack if need virtual wallet derivation rpc. up to fe to decide when. closing not done for now. will align to more detailed solution when will be here, split over fe and this repo.
