### ISSUE TITLE
XCVM add Swap instruction

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/composable#3944]
**Motivation**

https://github.com/ComposableFi/composable/issues/3825#issuecomment-1648293458

**Suggested Solution**

Implement swap and hardcode well known pools.

**Alternatives**

XCVM IBC own chane OR ICS27 + batch (for transfe and swap). Or 2 transactions form user wallet.

**Comment by mina86** [comment]
Based on my understanding, alternative solution is to make Spawn instruction require that a new context is created on the target chain (i.e. an unused salt is used) if the Spawn involves assets transfer.  This way, if someone Spawns a program they don’t have access to any other funds than the ones they transferred.  On the other hand, Spawn that doesn’t involve transfer can be verified and thus can access interpreter contexts owned by the sender.  At this time I have no strong intuition as to which is easier to implement; it may very well be custom Swap instruction.

**Comment by dzmitry-lahoda** [comment]
so pr plan is next:
1. pr config and cw messages for osmosis swap kind
2. compiled osmosis swaps
3. follow init deploy with pool for pica/osmo
4. test out all pieces and end the work

**Comment by dzmitry-lahoda** [comment]
donw
