### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by bengalmozzi** [ComposableFi/composable#3961]
**Description**

_Tell us what happened. In particular, be specific about any changes you made to this template.
Ideally, provide a link to your project's GitHub repository. Please note that we are not able to
support all conceivable changes to this template project, but the more information you are able to
provide the more equipped we will be to help._

**Steps to Reproduce**

_Replace the example steps below with actual steps to reproduce the bug you're reporting._

**Expected vs. Actual Behavior**

_What did you expect to happen after you followed the steps you described in the last section? What
actually happened?_

**Environment**

_Describe the environment in which you encountered this bug. Use the list below as a starting point
and add additional information if you think it's relevant._

- Operating system:
- Template version/tag:
- Rust version (run `rustup show`):

**Logs, Errors or Screenshots**

_Please provide the text of any logs or errors that you experienced; if
applicable, provide screenshots to help illustrate the problem._

**Additional Information**

_Please add any other details that you think may help us solve your problem._

**Comment by josietyleung** [comment]
testing
