### ISSUE TITLE
CLI tool to work with contracts to return contract error to user #picasso #cosmwasm

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/composable#3973]
**Motivation**

When calling CW contracts on Picasso, errors returned are `VirtualMachine` and `Interpreter`. 
Under these errors, there are real reasons why error happens, `Like cannot stake because minimal stake is 100, but got 20`, or whatever.
This is essential to develop contracts on platform and may be even blocker for adoption.  

Cosmos CW is good at returning error description. Cosmos receives `dry-run` flag to get error in CLI.

**Suggested Solution**

When run CLI tool  (called ccw), and transactions fails, show real contract error, not dispatch extrinsic errors.

I do not know exact solution, but may appear need to build RPC receiving TX on top runtime to get these and show to user. Good place to look is RPC TX of EVM on DotSama. 

**Alternatives**

Like Solana does, publish all logs to public so that they can search and debug.
All these errors are in public.

Show errors in PD.js, issue is that many Cosmos people are heavy CLI users, not UI. I do not know how to extend Polkadot js and extrinsics to return errors.

**Additional Information**

Exact acceptance criteria would be provided when we start working on this.

**Comment by josietyleung** [comment]
@blasrodri we'll need someone from bridging team on this for XCVMv0 thanks

**Comment by dzmitry-lahoda** [comment]
oh, this is just usability fixes for cosmwasm in dotsama.

**Comment by dzmitry-lahoda** [comment]
from bridging, 

https://github.com/ComposableFi/composable/pull/3963

also in my pr for wasm termination i already have to hack around centauri memo handling as it does not support general json as per spec.

anf this one https://github.com/ComposableFi/centauri/issues/383

**Comment by dzmitry-lahoda** [comment]
i have not heard plans to make product out of picasso cw/ibc/cosmos compatubke system, so ok to close now.
