### ISSUE TITLE
Run Time Upgrade 

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/composable#4006]
### Goal: 
1. Oracle + multihop fixes 

### Progress:
- [x] review required PRs @kkast 
- [x] local testing @NOOB6942069 
- [x] finalise CI to merge @kkast 
- [x] build release candidate (including wasm file) @kkast 
- [x] upgrade + test on chopsticks both composable and picasso + ibc transfers @NOOB6942069" 
- [x] test on devnet or rococo @fl-y 
- [x] picasso-roccoco: @rjonczy 
  - [x]  node upgrade
  - [x]  RPC 
  - [x]  runtime upgrade
 - [x] put up maintanence pages on Pablo, Centauri & Picasso @fl-y 
 - [x] discord + telegram announcement @NOOB6942069 
- [x] composable: @rjonczy 
  - [x] all nodes upgrade
  - [x] all RPCs 
  - [x]  runtime upgrade
- [x] picasso-kusama: @rjonczy 
  - [x]  all nodes upgrade
  - [x] all RPCs
  - [x]  runtime upgrade
- [ ] confirm stability @rjonczy 
- [x] smoke test production @NOOB6942069 
- [ ] remove maintenance pages on Pablo & Picasso @fl-y 
- [ ] runtime upgrade hyperspace - all relayers @vmarkushin @rjonczy 
- [ ] remove maintenance page on Centauri @fl-y 
- [x] communicate to collators to upgrade to latest version @NOOB6942069 
- [x]  discord + telegram announcement @NOOB6942069

**Comment by kkast** [comment]
sre team needs to update all nodes +rpcs for composable + picasso  as part of RTU

**Comment by kkast** [comment]
Need to change "upgrade + test on chopsticks @NOOB6942069" to "upgrade + test on chopsticks + ibc transfers @NOOB6942069"

**Comment by kkast** [comment]
then we upgrade all relayers all the time

**Comment by blasrodri** [comment]
Robert will move our infra to Kubernetes. This will be a long work, but it will payoff. It will provide us with a simple mechanism to update our infra much faster, and to react upon things like a new docker image being added into the registry. It will certainly speed up deployment of RPCs + Hyperspace.

**Comment by kkast** [comment]
for fe and parachain common testing we 
1) start which.dev with previous release version
2) populate it with data
3) check fe works(it should)
4) do runtime upgrade with release wasm file
5) run automated tests
@fl-y @blasrodri

**Comment by dzmitry-lahoda** [comment]
k8s sucks for single nodes and p2p software and software which special purposes hardware(more dances around than doing usefull work). terraform, nix, amis, cloud inits, cloud formation are better.

**Comment by josietyleung** [comment]
closing as completed
