### ISSUE TITLE
CosmWasm precompiles for pemissionless assets registry #cw #cosmos #picasso

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/composable#4031]
**Motivation**

Cosmos chains allow CW contracts to call tokenfactory, which is permissionless analog of our assets/assets-registry.

**Suggested Solution**

Possible interfaces of Query and Execute for precompiles are here 

https://github.com/ComposableFi/composable/blob/main/code/parachain/frame/composable-traits/src/assets.rs#L37

**Alternatives**

No.

**Additional Information**

Only part of interface can be done until https://github.com/ComposableFi/composable/issues/3401

**Comment by josietyleung** [comment]
closing as no longer required
