### ISSUE TITLE
Cosmwasm Developer Guide

### ISSUE THREAD

**Issue by josietyleung** [ComposableFi/composable#4143]
Edit the current guide on our [docs](https://docs.composable.finance/developer-guides/cosmwasm-cli) to run the ccw-vm CLI.

The current CLI guide is well documented however the following edits are necessary to support CW projects to deploy on the ccw-vm:

- Installing nix (for running the chain locally) - adjust for running on rococo
- Setup Rococo: This should be a page by itself, need to show the easiest way to setup to run pallet-cosmwasm on rococo. Add RPC endpoint for Picasso rococo: wss://picasso-rococo-unrpc-lb.composablenodes.tech/ to the guide.
- Add guide for rococo faucet - redirect to matrix
Running pallet-cosmwasm in local - Need to adjust to run ccw-vm on rococo

Open Questions: 

We need to document how CW contracts/projects interact with the asset registry and other pallets. Who can do this?

Is it necessary to add steps to verify any contract from the chain?

Upgrade CosmWasm version?

**Comment by JafarAz** [comment]
Everything other than the open questions section is complete

**Comment by dzmitry-lahoda** [comment]
no need to upgrade now. but as soon as useful feature would be requested or need of fix. sure.

what is verify means? generally no need to do verifications.

interaction can be documented by kostya. but tlrd, we have bank and  no tokenfactory(assets precompile).
