### ISSUE TITLE
IBC Tests

### ISSUE THREAD

**Issue by vladislav-terzi** [ComposableFi/composable#4228]
Need a bit of rework and ibc hooks might need support from @dzmitry-lahoda as well

**Comment by vladislav-terzi** [comment]
PR opened but changes are unable to be tested on devnet, in contact with @dzmitry-lahoda

**Comment by dzmitry-lahoda** [comment]
tbh we should test not hooks but user flows and scenarios. find out what path is prio and let solve it to be non flaky ci tested.

**Comment by dzmitry-lahoda** [comment]
hooks where some else. but please do not talk about test to low level. we have multihop transfers and swaps.
