### ISSUE TITLE
Connect Testnet-4 to Goerli

### ISSUE THREAD

**Issue by JafarAz** [ComposableFi/composable#4242]
We need to replicate the exact setup existing with Ethereum Sepolia with Ethereum Goerli. 

Ethereum Goerli is another testnet developers use to test and deploy Ethereum smart contracts.

1. Sync with the Goerli node
2. Upload IBC contract on Ethereum
3.  Create the clients/connections via Hyperspace from testnet 4.

**Comment by Ciejo** [comment]
The goerli node is up and running. Today we will upload the IBC contract.
