### ISSUE TITLE
Creation of devnet between polkadot and composable

### ISSUE THREAD

**Issue by Ciejo** [ComposableFi/composable#4270]

**Comment by dzmitry-lahoda** [comment]
if you will use nix, I drafted here https://github.com/ComposableFi/composable/pull/4271  

likely need setup of genesis according staking rules.

**Comment by dzmitry-lahoda** [comment]
provided video on bow to run devnet local or codespace with fast westend. so seems we target kusama too.

given these 2 things, closing issue now.

please reopen if i am mistaken.
