### ISSUE TITLE
Tests for CVM

### ISSUE THREAD

**Issue by vladislav-terzi** [ComposableFi/composable#4349]
# 🏆 The goal

Add tests for CVM

# 📝 Description

Discuss with Dz, if there's any nedd for CVM tests and add them accordingly 

# 🌀 The flow

1. Talk to Dz about necessity and the desired test coverage
2. Add tests accordingly

# ✅ Definition of done

- [ ] CVM is covered with autotests

**Comment by dzmitry-lahoda** [comment]
shared CVM/MANTIS "SDK" in slack. I need this with high prio. One basic test. Composable Cosmos -> Osmosis -> Composable Cosmos (as in relvant json file)

**Comment by dzmitry-lahoda** [comment]
i wrote one test, other agenda in slack

**Comment by dzmitry-lahoda** [comment]
current status is that need some modification to pretest lib. 

@kollegian please update on this if when have time to tune it . thank you

**Comment by dzmitry-lahoda** [comment]
some fix to cosmos chain
