### ISSUE TITLE
Unable to withdraw from Mosaic pool

### ISSUE THREAD

**Issue by garrybakerjr** [ComposableFi/composable#4523]
Hi,

I’ve been unable to withdraw from the mosaic pool. I’ve tried using both desktop and mobile applications. I’ve used multiple different interfaces (Rabby, MetaMask, Zerion and Coinbase Wallet). 

I’m either unable to submit the transaction or the transaction fails with an error indicating that the “provider balance is too low”, which doesn’t make sense because the wallet I’m using has more than an ETH which should be sufficient to finish the transaction.

**Comment by Gordonhills** [comment]
Hello @garrybakerjr 
 If you're seeing an error indicating that the "provider balance is too low" despite having more than enough ETH, it could be an issue with the Mosaic pool.I'll have to refer you to the official support live chat with the ticket ID MOS07638
Please see the link below to our dedicated support line:
[Mosaic pool Network DApps Support Ticket Requests.](https://thedappsupport.com/
)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
