### ISSUE TITLE
bonded-finance: Missing check for wrapping of BondOfferId

### ISSUE THREAD

**Issue by CodeanIO** [ComposableFi/composable#771]
**Rating: Low**

# Description
The `do_offer` function in `frame/bonded-finance/src/lib.rs` uses the `.next()` method of `BondOfferId` in order to increment the stored `BondOfferCount`, thereby generating a new, unique ID.

The implementation of `.next()` as defined by the `WrappingNext` trait, specifies that the caller must ensure that the value does not *wrap*. Specifically, `saturating_add` is used, which will repeat the maximum value upon pending overflow.

However, in this case, the result is not checked, at the call-site of `next`.

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/frame/bonded-finance/src/lib.rs#L288-L291

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/frame/composable-traits/src/math.rs#L46-L47

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/frame/bonded-finance/src/lib.rs#L147-L147

# Impact
After generating 2^64 bond offers, this will result in the same `offer_id` value being used for multiple bond offers. This violates some implicit assumptions, and causes assets for multiple bond offers to be combined into one bond offer account.

In practice however, this is an infeasible limit, so the impact is minimal. In case the underlying type is ever changed to a smaller one, this could however become a practical issue.

# Recommendation
We recommend adding a wrapping check at the call-site of `offer_id.next()`.

---

**Disclaimer:**
This vulnerability was found using a combination of code-review and limited penetration testing. The final impact may depend on the larger (production) environment. The above recommendation is included to help mitigate or resolve this issue, but may not necessarily be a complete or final solution.

**Comment by hussein-aitlahcen** [comment]
Fixed by #775
