### ISSUE TITLE
bonded-finance: Dali and Picasso runtime configuration mismatch with technical specification

### ISSUE THREAD

**Issue by CodeanIO** [ComposableFi/composable#772]
**Rating: None**

# Description
Several types are differently configured then specified in the technical specifications for both the `dali` and `picasso` runtime.

- `BondOfferId` has type `u64` while the specifications allow `u64` or `u128`
- `AdminOrigin` has type `EnsureRoot<AccountId>` instead of `RootOrHalfCouncil`
- `MinReward` has type 10 or 100 times PICA balance instead of `Get<Balance>`
- `Stake` has type 10 PICA balance instead of `Get<Balance>`
- `Duration` is not configurable but is specified in the technical specifications

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/runtime/dali/src/lib.rs#L830-L830

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/runtime/picasso/src/lib.rs#L745-L745

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/runtime/dali/src/lib.rs#L825-L825

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/runtime/dali/src/lib.rs#L831-L831

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/runtime/dali/src/lib.rs#L826-L826

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/runtime/picasso/src/lib.rs#L740-L740

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/runtime/picasso/src/lib.rs#L741-L741

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/runtime/picasso/src/lib.rs#L746-L746

# Impact
There does not appear to be a concrete security-related impact, and some of the types are conceptually the same. Nevertheless, assumptions based on these types might be violated.

# Recommendation
We recommend making sure that the type definitions and technical specification match, in order to avoid confusion.

---

**Disclaimer:**
This vulnerability was found using a combination of code-review and limited penetration testing. The final impact may depend on the larger (production) environment. The above recommendation is included to help mitigate or resolve this issue, but may not necessarily be a complete or final solution.

**Comment by hussein-aitlahcen** [comment]
Fixed by #775
