### ISSUE TITLE
crowdloan-rewards: Integer overflows in `do_populate`

### ISSUE THREAD

**Issue by CodeanIO** [ComposableFi/composable#774]
**Rating: Low**

# Description
The `do_populate` function in `frame/crowdloan-rewards/src/lib.rs` contains some logic which calculates the total reward amount (`total_rewards`), and the total amount of contributors (`total_contributors`).

The calculation is performed using a simple fold lambda, which makes use of the `+` operator for both fields. As this operator does not perform bounds checking, the unsigned integer values can overflow, leading to unexpected behavior when these totals are queried by external systems or people.

Specifically, one can pass a vector with more than 2^16 components to overflow `total_contributors`, and a total amount of rewards larger than 2^128 to overflow `total_rewards`. The latter is more likely to occur and feasible with a vector with just two rewards with a sum larger than 2^128.

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/frame/crowdloan-rewards/src/lib.rs#L298-L298

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/frame/crowdloan-rewards/src/lib.rs#L296-L296

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/frame/crowdloan-rewards/src/lib.rs#L304-L311

https://github.com/ComposableFi/composable/blob/35ec6680d07c08c207f8b3b0dc349cc8163000f1/frame/crowdloan-rewards/src/lib.rs#L314-L321

# Impact
As the `populate` extrinsic (and hence `do_populate`) can only be called from an `AdminOrigin` (i.e. `EnsureRootOrHalfCouncil`), the impact is quite limited.

# Recommendation
We recommend using SafeArithmetic or using other means to verify that no overflow has occured on `total_rewards`.

In order to prevent the overflow on `total_contributors`, we recommend checking the size of the input vector against the maximum value of `TotalContributors`.

---

**Disclaimer:**
This vulnerability was found using a combination of code-review and limited penetration testing. The final impact may depend on the larger (production) environment. The above recommendation is included to help mitigate or resolve this issue, but may not necessarily be a complete or final solution.

**Comment by hussein-aitlahcen** [comment]
Fixed by #693
