### ISSUE TITLE
Lending Feedback

### ISSUE THREAD

**Issue by KaiserKarel** [ComposableFi/composable#82]
## traits/oracle.rs

- [x] The oracle trait does not specify how to handle decimal point. perhaps it should be altered to:

https://github.com/ComposableFi/composable-pallets/blob/649cf366adffa53f8ab1d1c593b3b34cca3b4dff/frame/composable-traits/src/oracle.rs#L3-L16

```rust
        /// How much `in` currency should one have to get `amount` unit `of` currency
	/// Error is returned if currency not supported or price information not available.
	/// `in` currency some well known shared (stable) currency.
	/// Consumers may assume can get price of wrapped tokens:
	/// ```python
	/// price(wrap_1(wrap_2(wrap_3((btc))) = price(btc) * stock_dilution_1_ratio * stock_dilution_2_ratio * stock_dilution_3_ratio
	/// ``
	fn get_price(of: &Self::AssetId, amount: Self::Balance) -> Result<(Self::Balance, Self::Timestamp), DispatchError>;
```

## traits/lending.rs
- [x] Some minor spelling/style, will make a PR with my suggestions.

## traits/liquidation
- [x] Spelling of filename is incorrect ;)

- [x] I do not think that the lending protocol is capable of determining the fee, as that is dex specific. 

https://github.com/ComposableFi/composable-pallets/blob/649cf366adffa53f8ab1d1c593b3b34cca3b4dff/frame/composable-traits/src/liquidatation.rs#L14-L16

- [x] Should the Liquidate trait also handle routing? If so, it could be simplified to a single method, `liquidate`, and the implementer handles fee computation etc.

## traits/rate_model.rs
- [x] It seems that all models could implement a single trait, which exposes `get_borrow_rate`.

https://github.com/ComposableFi/composable-pallets/blob/649cf366adffa53f8ab1d1c593b3b34cca3b4dff/frame/composable-traits/src/rate_model.rs#L386

- [x] That seems to be related to cargo fmt

https://github.com/ComposableFi/composable-pallets/blob/903c455ef72f84e405b74e1a193d4077bf6bffa4/frame/lending/src/lib.rs#L239

- [x] Each of the event fields may be named, which avoids confusion:

```rust
pub enum Event<T: Config> {
    /// Event emitted when new lending market is created.
    NewMarketCreated {
	market_id: MarketIndex,
	vault_id: T::VaultId,
	manager: T::AccountId,
	borrow_asset_id: T::AssetId,
	collateral_asset_id: T::AssetId,
	reserved_factor: Perquintill,
	collateral_factor: NormalizedCollateralFactor,
    },
    ...
```		

- [x] How exactly does `MarketDebtCurrency` work?

**Comment by dzmitry-lahoda** [comment]
things seems done, currency stuff discussed in slack and moved as some part task to click up
