### ISSUE TITLE
Lending Pallet: Flash loans/Short term loands

### ISSUE THREAD

**Issue by KaiserKarel** [ComposableFi/composable#83]
The lending pallet does not yet handle loans being paid back within the same block (it uses the `on_initialize` and `on_finalize` hooks to compute interest). Currently someone can take out a loan, do stuff, and pay it back within the s same block without paying interest. We can of course disallow this, but it is a neat feature for arbitrage. Better would be to charge a minimum interest fee, say three blocks worth for any loan if we want to disincentive this, or just the regular block fee if we want to incentive.

Will write/think a bit more about this. Using the  `on_initialize` and `on_finalize` hooks means that the funds are calculated as if in use for the entire block, however if the funds are returned within the same block, someone else could use them as well

```
| ------------------------ block 1 ---------------------------------------------------|---------------------------------------------| 
|TX a ( take loan -> Do Stuff -> return loan) ----> TX b ( take loan)                 | TX c ( return loan                          |
```
TX a does not loan the funds for an entire block, just for a part of it.

**Comment by dzmitry-lahoda** [comment]
disallowed right now. @KaiserKarel could you create vNEXT parent task for this?

**Comment by KaiserKarel** [comment]
Yeah, I've added flash loans to the v2 roadmap
