### ISSUE TITLE
Refactor `ibc-rs` and integrate Beefy Light Client

### ISSUE THREAD

**Issue by Wizdave97** [ComposableFi/composable#977]
The current state of `ibc-rs` would not allow the integration of beefy light client seamlessly, hence the need for a refactor.

Link to issue here https://github.com/ComposableFi/ibc-rs/issues/1
Link to PR: https://github.com/ComposableFi/ibc-rs/pull/4

**Comment by seunlanlege** [comment]
I think this issue should actually be tracked on informalsystems/ibc-rs instead of our fork

**Comment by seunlanlege** [comment]
Trying to avoid maintenance costs, everything we do should eventually be upstreamed

**Comment by Wizdave97** [comment]
PR for this is open here https://github.com/ComposableFi/ibc-rs/pull/4
